# Generated by Django 6.0.2 on 2026-03-13 09:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0053_seed_purchasing_permissions'),
        ('inventory', '0008_rename_inventory_in_status_8d84cb_idx_inventory_r_status_c8c2fd_idx_and_more'),
        ('products', '0012_bundlepricechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(blank=True, default='')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('doc_type', models.CharField(default='PO', max_length=20)),
                ('order_date', models.DateField(db_index=True)),
                ('expected_receipt_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã gửi duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('PARTIAL_RECEIVED', 'Nhập kho một phần'), ('RECEIVED', 'Đã nhập đủ'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=30)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('supplier_snapshot', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('payment_terms_days', models.IntegerField(default=30)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('notes', models.TextField(blank=True, default='')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_approved', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouselocation')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_owned', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_rejected', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_submitted', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'purchasing_purchase_orders',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('internal_product_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('product_snapshot', models.JSONField(blank=True, default=dict)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('qty', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18)),
                ('received_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='products.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
            ],
            options={
                'db_table': 'purchasing_purchase_order_lines',
                'ordering': ['purchase_order_id', 'line_number'],
                'unique_together': {('purchase_order', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(blank=True, default='')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('receipt_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('POSTED', 'Đã ghi sổ'), ('CANCELLED', 'Đã hủy')], db_index=True, default='POSTED', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=200)),
                ('supplier_snapshot', models.JSONField(blank=True, default=dict)),
                ('total_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('note', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.warehouselocation')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts_posted', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipts_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'purchasing_purchase_receipts',
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('product_snapshot', models.JSONField(blank=True, default=dict)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('inventory_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_receipt_lines', to='inventory.inventorytransaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipt_lines', to='products.product')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='purchasing.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchasereceipt')),
            ],
            options={
                'db_table': 'purchasing_purchase_receipt_lines',
                'ordering': ['receipt_id', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(blank=True, default='')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã NCC')),
                ('name', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Công ty')),
                ('tax_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã số thuế')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='Điện thoại')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, default='', verbose_name='Địa chỉ')),
                ('contact_person', models.CharField(blank=True, default='', max_length=100, verbose_name='Người liên hệ')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30, verbose_name='SĐT liên hệ')),
                ('payment_terms_days', models.IntegerField(default=30, verbose_name='Hạn thanh toán (ngày)')),
                ('is_preferred', models.BooleanField(default=False, verbose_name='NCC ưu tiên')),
                ('rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Đánh giá')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_suppliers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_suppliers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchasing_suppliers',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchasing.supplier'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['code'], name='purchasing__code_bd125a_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['receipt_date'], name='purchasing__receipt_09fe24_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['status'], name='purchasing__status_58be87_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceipt',
            index=models.Index(fields=['purchase_order'], name='purchasing__purchas_356dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptline',
            index=models.Index(fields=['receipt', 'line_number'], name='purchasing__receipt_a38957_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptline',
            index=models.Index(fields=['product'], name='purchasing__product_1ba139_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasereceiptline',
            unique_together={('receipt', 'line_number')},
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['code'], name='purchasing__code_118042_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='purchasing__name_a7f50a_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company_name'], name='purchasing__company_d7c4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tax_code'], name='purchasing__tax_cod_4f8537_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['is_active'], name='purchasing__is_acti_fac6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['code'], name='purchasing__code_e69e56_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['order_date'], name='purchasing__order_d_424ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['expected_receipt_date'], name='purchasing__expecte_3ca397_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchasing__status_3ebde7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['supplier'], name='purchasing__supplie_af416e_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['team'], name='purchasing__team_id_1d8d13_idx'),
        ),
    ]
