# Generated by Django 6.0.2 on 2026-03-14 17:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_bundlepricechange'),
        ('purchasing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPurchasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('uom', models.CharField(blank=True, default='', max_length=20)),
                ('effective_from', models.DateField(db_index=True)),
                ('effective_to', models.DateField(blank=True, db_index=True, null=True)),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_purchase_prices_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_purchase_prices', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, help_text='Null = giá chuẩn chung', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_purchase_prices', to='purchasing.supplier')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_purchase_prices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bảng giá NVL',
                'verbose_name_plural': 'Bảng giá nguyên vật liệu',
                'db_table': 'purchasing_material_purchase_prices',
                'ordering': ['-effective_from', 'product', 'supplier'],
                'indexes': [models.Index(fields=['product'], name='purchasing__product_eae9e2_idx'), models.Index(fields=['supplier'], name='purchasing__supplie_54dd33_idx'), models.Index(fields=['effective_from', 'effective_to'], name='purchasing__effecti_c9dfa6_idx')],
            },
        ),
    ]
