# Generated by Django 6.0.2 on 2026-03-30 11:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_bundlepricechange'),
        ('purchasing', '0004_add_purchase_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
        migrations.CreateModel(
            name='PurchaseOrderLineMaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_item_id', models.BigIntegerField(db_index=True)),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchasing_po_line_material_allocations',
                'ordering': ['purchase_order_line_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptLineMaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_item_id', models.BigIntegerField(db_index=True)),
                ('allocated_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchasing_receipt_line_material_allocations',
                'ordering': ['purchase_receipt_line_id', 'id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_request_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='purchasing.purchaserequestline'),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='bundle_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='bundles_per_pallet',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='pallet_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereceiptline',
            name='units_per_bundle',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='sales_material_plan_item_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestline',
            name='source_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã gửi'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['purchase_order', 'line_number'], name='purchasing__purchas_898fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['product'], name='purchasing__product_ef18a3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderline',
            index=models.Index(fields=['purchase_request_line'], name='purchasing__purchas_c24fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestline',
            index=models.Index(fields=['purchase_request', 'line_number'], name='purchasing__purchas_9f5788_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestline',
            index=models.Index(fields=['product'], name='purchasing__product_fde165_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaserequestline',
            index=models.Index(fields=['sales_material_plan_item_id'], name='purchasing__sales_m_cce88e_idx'),
        ),
        migrations.AddField(
            model_name='purchaseorderlinematerialallocation',
            name='purchase_order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='purchasing.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='purchasereceiptlinematerialallocation',
            name='purchase_receipt_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_allocations', to='purchasing.purchasereceiptline'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderlinematerialallocation',
            index=models.Index(fields=['purchase_order_line'], name='purchasing__purchas_563a59_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderlinematerialallocation',
            index=models.Index(fields=['plan_item_id'], name='purchasing__plan_it_09fe65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderlinematerialallocation',
            unique_together={('purchase_order_line', 'plan_item_id')},
        ),
        migrations.AddIndex(
            model_name='purchasereceiptlinematerialallocation',
            index=models.Index(fields=['purchase_receipt_line'], name='purchasing__purchas_b56124_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereceiptlinematerialallocation',
            index=models.Index(fields=['plan_item_id'], name='purchasing__plan_it_77586d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchasereceiptlinematerialallocation',
            unique_together={('purchase_receipt_line', 'plan_item_id')},
        ),
            ],
        ),
    ]
