from django.db import migrations


APPLY_0005_DATABASE_SCHEMA_SQL = """
ALTER TABLE purchasing_purchase_order_lines
    ADD COLUMN IF NOT EXISTS purchase_request_line_id bigint NULL;

ALTER TABLE purchasing_purchase_receipt_lines
    ADD COLUMN IF NOT EXISTS bundle_count integer NULL,
    ADD COLUMN IF NOT EXISTS units_per_bundle numeric(18, 4) NULL,
    ADD COLUMN IF NOT EXISTS pallet_count integer NULL,
    ADD COLUMN IF NOT EXISTS bundles_per_pallet numeric(18, 4) NULL;

ALTER TABLE purchasing_requests
    ADD COLUMN IF NOT EXISTS cancel_reason text NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS cancelled_at timestamp with time zone NULL,
    ADD COLUMN IF NOT EXISTS cancelled_by_id bigint NULL;

ALTER TABLE purchasing_request_lines
    ADD COLUMN IF NOT EXISTS sales_material_plan_item_id bigint NULL,
    ADD COLUMN IF NOT EXISTS source_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS purchasing_po_line_material_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_order_line_id bigint NOT NULL,
    plan_item_id bigint NOT NULL,
    allocated_qty numeric(18, 4) NOT NULL DEFAULT 0,
    note varchar(255) NOT NULL DEFAULT '',
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS purchasing_receipt_line_material_allocations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_receipt_line_id bigint NOT NULL,
    plan_item_id bigint NOT NULL,
    allocated_qty numeric(18, 4) NOT NULL DEFAULT 0,
    note varchar(255) NOT NULL DEFAULT '',
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS purchasing__purchas_898fa0_idx
    ON purchasing_purchase_order_lines (purchase_order_id, line_number);
CREATE INDEX IF NOT EXISTS purchasing__product_ef18a3_idx
    ON purchasing_purchase_order_lines (product_id);
CREATE INDEX IF NOT EXISTS purchasing__purchas_c24fa3_idx
    ON purchasing_purchase_order_lines (purchase_request_line_id);

CREATE INDEX IF NOT EXISTS purchasing_requests_cancelled_by_id_idx
    ON purchasing_requests (cancelled_by_id);

CREATE INDEX IF NOT EXISTS purchasing__purchas_9f5788_idx
    ON purchasing_request_lines (purchase_request_id, line_number);
CREATE INDEX IF NOT EXISTS purchasing__product_fde165_idx
    ON purchasing_request_lines (product_id);
CREATE INDEX IF NOT EXISTS purchasing__sales_m_cce88e_idx
    ON purchasing_request_lines (sales_material_plan_item_id);

CREATE INDEX IF NOT EXISTS purchasing__purchas_563a59_idx
    ON purchasing_po_line_material_allocations (purchase_order_line_id);
CREATE INDEX IF NOT EXISTS purchasing__plan_it_09fe65_idx
    ON purchasing_po_line_material_allocations (plan_item_id);
CREATE UNIQUE INDEX IF NOT EXISTS purchasing_po_line_material_allocations_line_plan_uniq
    ON purchasing_po_line_material_allocations (purchase_order_line_id, plan_item_id);

CREATE INDEX IF NOT EXISTS purchasing__purchas_b56124_idx
    ON purchasing_receipt_line_material_allocations (purchase_receipt_line_id);
CREATE INDEX IF NOT EXISTS purchasing__plan_it_77586d_idx
    ON purchasing_receipt_line_material_allocations (plan_item_id);
CREATE UNIQUE INDEX IF NOT EXISTS purchasing_receipt_line_material_allocations_line_plan_uniq
    ON purchasing_receipt_line_material_allocations (purchase_receipt_line_id, plan_item_id);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'purchasing_pol_purchase_request_line_fk'
            AND conrelid = 'purchasing_purchase_order_lines'::regclass
    ) THEN
        ALTER TABLE purchasing_purchase_order_lines
            ADD CONSTRAINT purchasing_pol_purchase_request_line_fk
            FOREIGN KEY (purchase_request_line_id)
            REFERENCES purchasing_request_lines (id)
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'purchasing_requests_cancelled_by_fk'
            AND conrelid = 'purchasing_requests'::regclass
    ) THEN
        ALTER TABLE purchasing_requests
            ADD CONSTRAINT purchasing_requests_cancelled_by_fk
            FOREIGN KEY (cancelled_by_id)
            REFERENCES users (id)
            ON DELETE SET NULL
            DEFERRABLE INITIALLY DEFERRED;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'purchasing_receipt_lines_bundle_count_nonneg'
            AND conrelid = 'purchasing_purchase_receipt_lines'::regclass
    ) THEN
        ALTER TABLE purchasing_purchase_receipt_lines
            ADD CONSTRAINT purchasing_receipt_lines_bundle_count_nonneg
            CHECK (bundle_count >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'purchasing_receipt_lines_pallet_count_nonneg'
            AND conrelid = 'purchasing_purchase_receipt_lines'::regclass
    ) THEN
        ALTER TABLE purchasing_purchase_receipt_lines
            ADD CONSTRAINT purchasing_receipt_lines_pallet_count_nonneg
            CHECK (pallet_count >= 0);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'purchasing_po_alloc_line_fk'
            AND conrelid = 'purchasing_po_line_material_allocations'::regclass
    ) THEN
        ALTER TABLE purchasing_po_line_material_allocations
            ADD CONSTRAINT purchasing_po_alloc_line_fk
            FOREIGN KEY (purchase_order_line_id)
            REFERENCES purchasing_purchase_order_lines (id)
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'purchasing_receipt_alloc_line_fk'
            AND conrelid = 'purchasing_receipt_line_material_allocations'::regclass
    ) THEN
        ALTER TABLE purchasing_receipt_line_material_allocations
            ADD CONSTRAINT purchasing_receipt_alloc_line_fk
            FOREIGN KEY (purchase_receipt_line_id)
            REFERENCES purchasing_purchase_receipt_lines (id)
            ON DELETE CASCADE
            DEFERRABLE INITIALLY DEFERRED;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_purchaseorderlinematerialallocation_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=APPLY_0005_DATABASE_SCHEMA_SQL,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
