# Generated by Django 6.0.2 on 2026-06-24 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_inventorytransaction_stocktake_and_more'),
        ('products', '0019_product_item_type'),
        ('purchasing', '0006_restore_0005_database_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='reversal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='reversed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns_reversed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='source_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='purchasing.purchasereceipt'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_issue_lines', to='inventory.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='reversal_inventory_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_reversal_lines', to='inventory.inventorytransaction'),
        ),
        migrations.AddField(
            model_name='purchasereturnline',
            name='source_receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='purchasing.purchasereceiptline'),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('POSTED', 'Đã vào sổ'), ('REVERSED', 'Đã đảo'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['source_receipt'], name='purchasing__source__3c5508_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnline',
            index=models.Index(fields=['source_receipt_line'], name='purchasing__source__e84d50_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnline',
            index=models.Index(fields=['inventory_transaction'], name='purchasing__invento_c7137d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnline',
            index=models.Index(fields=['reversal_inventory_transaction'], name='purchasing__reversa_b8ed61_idx'),
        ),
    ]
