# Generated by Django 5.0 on 2026-01-29 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0028_emailtemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã đơn vị (CAI, HOP, KIEN)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Tên đơn vị (Cái, Hộp, Kiện)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Unit',
                'verbose_name_plural': 'Product Units',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã danh mục', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Tên danh mục', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Danh mục cha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã sản phẩm (auto từ NumberSequence)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Tên sản phẩm', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Mô tả chi tiết')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Thông số kỹ thuật: chiều dài, rộng, cao, độ dày, chất liệu...')),
                ('images', models.JSONField(blank=True, default=list, help_text='Danh sách URLs ảnh sản phẩm')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='Giá vốn', max_digits=15)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Giá bán', max_digits=15)),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='Tồn kho tối thiểu', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued')], default='DRAFT', help_text='Trạng thái sản phẩm', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Người sở hữu (Data Scope)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, help_text='Team sở hữu (Data Scope)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_products', to='core.team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productunit')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=1, help_text='Số lượng tối thiểu áp dụng', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Đơn giá', max_digits=15)),
                ('effective_from', models.DateField(help_text='Ngày bắt đầu hiệu lực')),
                ('effective_to', models.DateField(blank=True, help_text='Ngày kết thúc (null = không hết hạn)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Khách hàng cụ thể (null = giá chung)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_pricings', to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Pricing',
                'verbose_name_plural': 'Product Pricings',
                'ordering': ['product', '-effective_from'],
                'unique_together': {('product', 'customer', 'min_quantity', 'effective_from')},
            },
        ),
    ]
