# Generated by Django 5.0 on 2026-01-30 08:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_enable_trigram'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productpricing',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productpricing',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productpricing',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AddField(
            model_name='product',
            name='box_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kiểu'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_count',
            field=models.IntegerField(default=0, verbose_name='Số màu'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='HHCĐ (đ/cái)'),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='HH%'),
        ),
        migrations.AddField(
            model_name='product',
            name='component_quantity',
            field=models.IntegerField(default=1, verbose_name='Số lượng đi kèm'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_tolerance',
            field=models.CharField(blank=True, max_length=50, verbose_name='+/-'),
        ),
        migrations.AddField(
            model_name='product',
            name='film_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã phim'),
        ),
        migrations.AddField(
            model_name='product',
            name='film_file_url',
            field=models.URLField(blank=True, verbose_name='Link file phim (PDF)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_set',
            field=models.BooleanField(default=False, verbose_name='Là bộ sản phẩm'),
        ),
        migrations.AddField(
            model_name='product',
            name='mold_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mã khuôn'),
        ),
        migrations.AddField(
            model_name='product',
            name='mold_file_url',
            field=models.URLField(blank=True, verbose_name='Link file khuôn (PDF)'),
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='product',
            name='note_other',
            field=models.TextField(blank=True, verbose_name='Ghi chú khác'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.product', verbose_name='Thùng mẹ'),
        ),
        migrations.AddField(
            model_name='product',
            name='process_be',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bế (cái/giờ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='process_boi',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bồi (cái/giờ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='process_can_mang',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cán màng (cái/giờ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='process_chap',
            field=models.IntegerField(blank=True, null=True, verbose_name='Chạp (cái/giờ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='process_dan',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dán (cái/giờ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='process_dong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Đóng (cái/giờ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='process_in',
            field=models.IntegerField(blank=True, null=True, verbose_name='In (cái/giờ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='process_khac',
            field=models.IntegerField(blank=True, null=True, verbose_name='Khác (cái/giờ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='process_xa',
            field=models.IntegerField(blank=True, null=True, verbose_name='Xả (cái/giờ)'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_order',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kích thước ĐH'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_production',
            field=models.CharField(blank=True, max_length=50, verbose_name='KTSX'),
        ),
        migrations.AddField(
            model_name='product',
            name='waterproof',
            field=models.CharField(blank=True, choices=[('', 'Không'), ('INSIDE', 'Trong'), ('OUTSIDE', 'Ngoài'), ('BOTH', '2 mặt')], default='', max_length=10, verbose_name='Chống thấm'),
        ),
        migrations.AddField(
            model_name='product',
            name='wave_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sóng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='Danh mục'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Mã hàng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vốn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_products', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tồn TT'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tên hàng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_products', to=settings.AUTH_USER_MODEL, verbose_name='Người sở hữu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Đơn giá'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang bán'), ('DISCONTINUED', 'Ngừng SX')], default='DRAFT', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='product',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_products', to='core.team', verbose_name='Nhóm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productunit', verbose_name='Đơn vị tính'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_products', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='products_code_770e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_name_6f9890_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['parent'], name='products_parent__0207e2_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
        migrations.DeleteModel(
            name='ProductPricing',
        ),
    ]
