# Generated by Django 6.0.2 on 2026-02-11 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_customer_indexes'),
        ('products', '0006_rebuild_search_text_process_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productboxtype',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Kiểu thùng', 'verbose_name_plural': 'Kiểu thùng'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Product Unit', 'verbose_name_plural': 'Product Units'},
        ),
        migrations.AlterModelOptions(
            name='productwave',
            options={'ordering': ['sort_order', 'code'], 'verbose_name': 'Loại sóng', 'verbose_name_plural': 'Loại sóng'},
        ),
        migrations.AddField(
            model_name='productboxtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_box_types', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='productboxtype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa (soft)'),
        ),
        migrations.AddField(
            model_name='productboxtype',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_product_box_types', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa'),
        ),
        migrations.AddField(
            model_name='productboxtype',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Thứ tự'),
        ),
        migrations.AddField(
            model_name='productboxtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_box_types', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_categories', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa (soft)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_product_categories', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Thứ tự sắp xếp'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_categories', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_units', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa (soft)'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_product_units', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Thứ tự sắp xếp'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_units', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='productwave',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_waves', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='productwave',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa (soft)'),
        ),
        migrations.AddField(
            model_name='productwave',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_product_waves', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa'),
        ),
        migrations.AddField(
            model_name='productwave',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Thứ tự'),
        ),
        migrations.AddField(
            model_name='productwave',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_waves', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_is_acti_cb485f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['team'], name='products_team_id_d297e8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_created_e1ba5f_idx'),
        ),
        migrations.AddIndex(
            model_name='productboxtype',
            index=models.Index(fields=['code'], name='product_box_code_3c63a0_idx'),
        ),
        migrations.AddIndex(
            model_name='productboxtype',
            index=models.Index(fields=['name'], name='product_box_name_5a36d0_idx'),
        ),
        migrations.AddIndex(
            model_name='productboxtype',
            index=models.Index(fields=['is_active'], name='product_box_is_acti_9d3a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='productboxtype',
            index=models.Index(fields=['created_at'], name='product_box_created_c03703_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['code'], name='product_cat_code_fe6111_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['name'], name='product_cat_name_d66187_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['is_active'], name='product_cat_is_acti_f5a665_idx'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['created_at'], name='product_cat_created_9c802d_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['code'], name='product_uni_code_8b2546_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['name'], name='product_uni_name_7daed3_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['is_active'], name='product_uni_is_acti_ed8a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['created_at'], name='product_uni_created_8d9de3_idx'),
        ),
        migrations.AddIndex(
            model_name='productwave',
            index=models.Index(fields=['code'], name='product_wav_code_806923_idx'),
        ),
        migrations.AddIndex(
            model_name='productwave',
            index=models.Index(fields=['name'], name='product_wav_name_55e500_idx'),
        ),
        migrations.AddIndex(
            model_name='productwave',
            index=models.Index(fields=['is_active'], name='product_wav_is_acti_6834c1_idx'),
        ),
        migrations.AddIndex(
            model_name='productwave',
            index=models.Index(fields=['created_at'], name='product_wav_created_6bfed9_idx'),
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_categories',
        ),
        migrations.AlterModelTable(
            name='productunit',
            table='product_units',
        ),
    ]
