# Generated by Django 6.0.2 on 2026-02-11 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_master_data_audit_soft_delete_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productboxtype',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Mã kiểu (unique trong bản ghi chưa xóa)'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(help_text='Mã danh mục (unique trong bản ghi chưa xóa)', max_length=20),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='code',
            field=models.CharField(help_text='Mã đơn vị (unique trong bản ghi chưa xóa)', max_length=10),
        ),
        migrations.AlterField(
            model_name='productwave',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Mã sóng (unique trong bản ghi chưa xóa)'),
        ),
        migrations.AddConstraint(
            model_name='productboxtype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='product_boxtype_code_uniq_active'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='product_cat_code_uniq_active'),
        ),
        migrations.AddConstraint(
            model_name='productunit',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='product_unit_code_uniq_active'),
        ),
        migrations.AddConstraint(
            model_name='productwave',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='product_wave_code_uniq_active'),
        ),
    ]
