# Generated by Django 6.0.2 on 2026-02-19 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_unique_code_ignore_soft_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('old_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('delta_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('delta_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('delta_cost_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('delta_sale_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('MANUAL', 'Thủ công'), ('IMPORT', 'Nhập dữ liệu'), ('API', 'API')], default='MANUAL', max_length=20)),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('APPLIED', 'Đã áp dụng')], default='APPLIED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_price_changes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_changes', to='products.product', verbose_name='Sản phẩm')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_price_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_price_changes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='product_pri_product_c43d82_idx'), models.Index(fields=['status', 'created_at'], name='product_pri_status_f5aa26_idx')],
            },
        ),
    ]
