# Generated by Django 6.0.2 on 2026-03-11 06:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_pricechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_mode', models.CharField(choices=[('PRIMARY_PRODUCT', 'Lấy theo sản phẩm mẹ/đại diện'), ('FIXED_BUNDLE', 'Giá bộ cố định'), ('SUM_COMPONENTS', 'Cộng từ các thành phần')], default='PRIMARY_PRODUCT', max_length=30, verbose_name='Kiểu tính giá bộ')),
                ('fixed_cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá vốn bộ cố định')),
                ('fixed_sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá bán bộ cố định')),
                ('commission_mode', models.CharField(choices=[('PRIMARY_PRODUCT', 'Lấy theo sản phẩm mẹ/đại diện'), ('FIXED_VALUES', 'Hoa hồng cố định theo bộ'), ('SUM_COMPONENTS', 'Cộng từ các thành phần')], default='PRIMARY_PRODUCT', max_length=30, verbose_name='Kiểu tính hoa hồng bộ')),
                ('fixed_commission_per_unit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='HHCĐ bộ cố định')),
                ('fixed_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='HH% bộ cố định')),
                ('delivery_rule', models.CharField(choices=[('STRICT_FULL_SET', 'Giao đồng bộ đủ bộ')], default='STRICT_FULL_SET', max_length=30, verbose_name='Quy tắc giao đồng bộ')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú bộ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_bundles', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('primary_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_bundles', to='products.product', verbose_name='Sản phẩm mẹ/chính')),
                ('sellable_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_config', to='products.product', verbose_name='Mã bán/bộ đại diện')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_bundles', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Bộ sản phẩm',
                'verbose_name_plural': 'Bộ sản phẩm',
                'db_table': 'product_bundles',
                'ordering': ['sellable_product__code'],
            },
        ),
        migrations.CreateModel(
            name='ProductBundleComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_per_bundle', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Số lượng trong 1 bộ')),
                ('is_required', models.BooleanField(default=True, verbose_name='Bắt buộc giao đủ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.productbundle', verbose_name='Bộ sản phẩm')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_memberships', to='products.product', verbose_name='Mã hàng thành phần')),
            ],
            options={
                'verbose_name': 'Thành phần bộ sản phẩm',
                'verbose_name_plural': 'Thành phần bộ sản phẩm',
                'db_table': 'product_bundle_components',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='productbundle',
            index=models.Index(fields=['pricing_mode'], name='product_bun_pricing_6ca836_idx'),
        ),
        migrations.AddIndex(
            model_name='productbundle',
            index=models.Index(fields=['commission_mode'], name='product_bun_commiss_2f54d5_idx'),
        ),
        migrations.AddIndex(
            model_name='productbundle',
            index=models.Index(fields=['delivery_rule'], name='product_bun_deliver_1f2a1b_idx'),
        ),
        migrations.AddIndex(
            model_name='productbundle',
            index=models.Index(fields=['is_active'], name='product_bun_is_acti_71b37e_idx'),
        ),
        migrations.AddIndex(
            model_name='productbundlecomponent',
            index=models.Index(fields=['bundle'], name='product_bun_bundle__ccbc32_idx'),
        ),
        migrations.AddIndex(
            model_name='productbundlecomponent',
            index=models.Index(fields=['component_product'], name='product_bun_compone_5c913b_idx'),
        ),
        migrations.AddIndex(
            model_name='productbundlecomponent',
            index=models.Index(fields=['is_required'], name='product_bun_is_requ_7b61a0_idx'),
        ),
        migrations.AddIndex(
            model_name='productbundlecomponent',
            index=models.Index(fields=['is_active'], name='product_bun_is_acti_ad3c7a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productbundlecomponent',
            unique_together={('bundle', 'component_product')},
        ),
    ]
