# Generated by Django 6.0.2 on 2026-03-11 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productbundle_productbundlecomponent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricechange',
            options={'ordering': ['-effective_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='pricechange',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricechange',
            name='batch_code',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pricechange',
            name='new_commission_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricechange',
            name='new_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pricechange',
            name='old_commission_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricechange',
            name='old_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='source',
            field=models.CharField(choices=[('SYSTEM', 'Hệ thống'), ('MANUAL', 'Thủ công'), ('IMPORT', 'Nhập dữ liệu'), ('API', 'API')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricechange',
            name='status',
            field=models.CharField(choices=[('PENDING_APPROVAL', 'Chờ duyệt'), ('APPROVED_SCHEDULED', 'Đã duyệt, chờ hiệu lực'), ('ACTIVE_APPLIED', 'Đang hiệu lực'), ('REJECTED', 'Từ chối'), ('SUPERSEDED', 'Đã bị thay thế')], default='ACTIVE_APPLIED', max_length=30),
        ),
        migrations.AlterField(
            model_name='productbundle',
            name='delivery_rule',
            field=models.CharField(choices=[('STRICT_FULL_SET', 'Giao đồng bộ đủ bộ'), ('NON_SYNC', 'Giao không đồng bộ')], default='STRICT_FULL_SET', max_length=30, verbose_name='Quy tắc giao đồng bộ'),
        ),
        migrations.AddIndex(
            model_name='pricechange',
            index=models.Index(fields=['product', 'effective_at'], name='product_pri_product_5da428_idx'),
        ),
        migrations.AddIndex(
            model_name='pricechange',
            index=models.Index(fields=['batch_code'], name='product_pri_batch_c_c22c3a_idx'),
        ),
    ]
