# Generated by Django 6.0.2 on 2026-03-31 03:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_bundlepricechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('ACTIVE', 'Đang áp dụng'), ('INACTIVE', 'Ngưng áp dụng')], db_index=True, default='DRAFT', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product_material_templates', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_templates', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_product_material_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_material_templates',
                'ordering': ['finished_product_id', '-is_default', '-version_no'],
                'unique_together': {('finished_product', 'version_no')},
            },
        ),
        migrations.CreateModel(
            name='ProductMaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=255)),
                ('material_role', models.CharField(choices=[('PRIMARY', 'Nguyên liệu chính'), ('SHARED', 'Vật tư dùng chung')], db_index=True, default='PRIMARY', max_length=20)),
                ('selection_rule', models.CharField(choices=[('ONE_OF', 'Chọn 1 trong nhiều'), ('ALL_REQUIRED', 'Bắt buộc tất cả')], db_index=True, default='ONE_OF', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('include_in_summary', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='products.productmaterialtemplate')),
            ],
            options={
                'db_table': 'product_material_groups',
                'ordering': ['template_id', 'sort_order', 'id'],
                'unique_together': {('template', 'group_code')},
            },
        ),
        migrations.CreateModel(
            name='ProductMaterialOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_snapshot', models.JSONField(blank=True, default=dict)),
                ('qty_per_unit', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('waste_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('priority_no', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.productmaterialgroup')),
                ('material_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_template_options', to='products.product')),
            ],
            options={
                'db_table': 'product_material_options',
                'ordering': ['group_id', 'priority_no', 'id'],
                'unique_together': {('group', 'material_product')},
            },
        ),
    ]
