# Generated by Django 6.0.2 on 2026-04-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_seed_operations_and_backfill_product_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_kind',
            field=models.CharField(choices=[('SPECIFIC', 'Mã riêng'), ('GENERIC', 'Mã chung')], default='SPECIFIC', max_length=20, verbose_name='Loại mã hàng'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_order_operations_review',
            field=models.BooleanField(default=False, verbose_name='Bắt buộc kiểm tra công đoạn khi lên đơn'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_order_spec',
            field=models.BooleanField(default=False, verbose_name='Bắt buộc xác nhận quy cách khi lên đơn'),
        ),
    ]
