# Generated by Django 6.0.2 on 2026-04-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_kind_order_review_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='print_color_1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Màu in 1 / mã màu'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_color_2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Màu in 2 / mã màu'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_color_3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Màu in 3 / mã màu'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_color_4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Màu in 4 / mã màu'),
        ),
        migrations.AddField(
            model_name='product',
            name='print_color_5',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Màu in 5 / mã màu'),
        ),
    ]
