# Generated by Django 6.0.2 on 2026-04-28 15:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_print_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('display_order', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('operation_code', models.CharField(blank=True, max_length=30)),
                ('operation_name', models.CharField(blank=True, max_length=100)),
                ('standard_rate_per_hour', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('note', models.TextField(blank=True)),
                ('step_type', models.CharField(choices=[('REQUIRED', 'Required'), ('OPTIONAL', 'Optional'), ('CHOOSE_ONE', 'Choose one'), ('PARALLEL', 'Parallel')], default='REQUIRED', max_length=20)),
                ('group_code', models.CharField(blank=True, default='', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('allow_parallel', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_steps', to='products.operation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_steps', to='products.product')),
                ('product_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_steps', to='products.productoperation')),
            ],
            options={
                'db_table': 'product_routing_steps',
                'ordering': ['product_id', 'step_no', 'display_order', 'id'],
                'indexes': [models.Index(fields=['product', 'step_no', 'display_order'], name='product_rou_product_587214_idx'), models.Index(fields=['operation'], name='product_rou_operati_e969db_idx'), models.Index(fields=['product_operation'], name='product_rou_product_c347e6_idx'), models.Index(fields=['operation_code'], name='product_rou_operati_230a11_idx'), models.Index(fields=['is_active'], name='product_rou_is_acti_4b2a1e_idx'), models.Index(fields=['step_type'], name='product_rou_step_ty_8ecb00_idx'), models.Index(fields=['group_code'], name='product_rou_group_c_eee0c9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('step_no__gt', 0)), name='product_routing_step_step_no_gt_0'), models.CheckConstraint(condition=models.Q(('display_order__gt', 0)), name='product_routing_step_display_order_gt_0'), models.CheckConstraint(condition=models.Q(('standard_rate_per_hour__gt', 0)), name='product_routing_step_rate_gt_0')],
            },
        ),
    ]
