--
-- PostgreSQL database dump
--

\restrict 6VMzZpnrkhW7oTr2PfqTcHPWudhEdqCPWbH7uej6fstAYamGRxEWIZz83RIJtJo

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: approval_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.approval_history (
    id bigint NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    entity_code character varying(50) NOT NULL,
    action character varying(20) NOT NULL,
    comments text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    level integer NOT NULL,
    user_id bigint
);


ALTER TABLE public.approval_history OWNER TO postgres;

--
-- Name: approval_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.approval_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.approval_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attachments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attachments (
    id bigint NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    file character varying(100) NOT NULL,
    filename character varying(255) NOT NULL,
    file_size integer NOT NULL,
    file_type character varying(100) NOT NULL,
    description text NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    uploaded_by_id bigint
);


ALTER TABLE public.attachments OWNER TO postgres;

--
-- Name: attachments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attachments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attachments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    entity_code character varying(50) NOT NULL,
    old_values jsonb,
    new_values jsonb,
    changed_fields jsonb NOT NULL,
    ip_address inet,
    user_agent text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.audit_logs OWNER TO postgres;

--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comment_reactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comment_reactions (
    id bigint NOT NULL,
    reaction_type character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    comment_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.comment_reactions OWNER TO postgres;

--
-- Name: comment_reactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comment_reactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_reactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    content text NOT NULL,
    mentions jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_deleted boolean NOT NULL,
    deleted_at timestamp with time zone,
    created_by_id bigint,
    parent_id bigint
);


ALTER TABLE public.comments OWNER TO postgres;

--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_roles (
    id bigint CONSTRAINT core_user_roles_id_not_null NOT NULL,
    user_id bigint CONSTRAINT core_user_roles_user_id_not_null NOT NULL,
    role_id bigint CONSTRAINT core_user_roles_role_id_not_null NOT NULL
);


ALTER TABLE public.users_roles OWNER TO postgres;

--
-- Name: core_user_roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.core_user_roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    company_name character varying(200) NOT NULL,
    tax_code character varying(50) NOT NULL,
    phone character varying(20) NOT NULL,
    email character varying(254) NOT NULL,
    address text NOT NULL,
    contact_person character varying(100) NOT NULL,
    contact_phone character varying(20) NOT NULL,
    payment_terms integer NOT NULL,
    credit_limit numeric(15,2) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    updated_by_id bigint,
    approved_at timestamp with time zone,
    approved_by_id bigint,
    rejected_at timestamp with time zone,
    rejected_by_id bigint,
    rejection_reason text NOT NULL,
    status character varying(20) NOT NULL,
    owner_id bigint,
    team_id bigint
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_q_ormq; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_q_ormq (
    id integer NOT NULL,
    key character varying(100) NOT NULL,
    payload text NOT NULL,
    lock timestamp with time zone
);


ALTER TABLE public.django_q_ormq OWNER TO postgres;

--
-- Name: django_q_ormq_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_q_ormq ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_q_ormq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_q_schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_q_schedule (
    id integer NOT NULL,
    func character varying(256) NOT NULL,
    hook character varying(256),
    args text,
    kwargs text,
    schedule_type character varying(2) NOT NULL,
    repeats integer NOT NULL,
    next_run timestamp with time zone,
    task character varying(100),
    name character varying(100),
    minutes smallint,
    cron character varying(100),
    cluster character varying(100),
    intended_date_kwarg character varying(100),
    CONSTRAINT django_q_schedule_minutes_check CHECK ((minutes >= 0))
);


ALTER TABLE public.django_q_schedule OWNER TO postgres;

--
-- Name: django_q_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_q_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_q_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_q_task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_q_task (
    name character varying(100) NOT NULL,
    func character varying(256) NOT NULL,
    hook character varying(256),
    args text,
    kwargs text,
    result text,
    started timestamp with time zone NOT NULL,
    stopped timestamp with time zone NOT NULL,
    success boolean NOT NULL,
    id character varying(32) NOT NULL,
    "group" character varying(100),
    attempt_count integer NOT NULL,
    cluster character varying(100)
);


ALTER TABLE public.django_q_task OWNER TO postgres;

--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: entity_tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.entity_tags (
    id bigint NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    tag_id bigint NOT NULL
);


ALTER TABLE public.entity_tags OWNER TO postgres;

--
-- Name: entity_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.entity_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.entity_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: export_templates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.export_templates (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    entity_type character varying(50) NOT NULL,
    columns jsonb NOT NULL,
    headers jsonb NOT NULL,
    is_default boolean NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint
);


ALTER TABLE public.export_templates OWNER TO postgres;

--
-- Name: export_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.export_templates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.export_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: import_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.import_logs (
    id bigint NOT NULL,
    entity_type character varying(50) NOT NULL,
    filename character varying(255) NOT NULL,
    total_rows integer NOT NULL,
    success_count integer NOT NULL,
    error_count integer NOT NULL,
    errors jsonb NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint
);


ALTER TABLE public.import_logs OWNER TO postgres;

--
-- Name: import_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.import_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.import_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    notification_type character varying(20) NOT NULL,
    title character varying(255) NOT NULL,
    message text NOT NULL,
    entity_type character varying(50) NOT NULL,
    entity_id integer,
    is_read boolean NOT NULL,
    read_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    actor_id bigint,
    recipient_id bigint NOT NULL
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: number_sequences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.number_sequences (
    id bigint NOT NULL,
    entity_type character varying(50) NOT NULL,
    prefix character varying(10) NOT NULL,
    current_number integer NOT NULL,
    padding integer NOT NULL,
    format_template character varying(50) NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.number_sequences OWNER TO postgres;

--
-- Name: number_sequences_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.number_sequences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.number_sequences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_policies; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.password_policies (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    min_length integer NOT NULL,
    require_uppercase boolean NOT NULL,
    require_lowercase boolean NOT NULL,
    require_digit boolean NOT NULL,
    require_special boolean NOT NULL,
    prevent_reuse_count integer NOT NULL,
    expire_days integer NOT NULL,
    force_change_first_login boolean NOT NULL,
    is_active boolean NOT NULL
);


ALTER TABLE public.password_policies OWNER TO postgres;

--
-- Name: password_policies_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.password_policies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_policies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.permissions (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(100) NOT NULL,
    resource character varying(50) NOT NULL,
    action character varying(50) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.permissions OWNER TO postgres;

--
-- Name: permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(50) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles_permissions (
    id bigint NOT NULL,
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL
);


ALTER TABLE public.roles_permissions OWNER TO postgres;

--
-- Name: roles_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: saved_views; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.saved_views (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    entity_type character varying(50) NOT NULL,
    filters jsonb NOT NULL,
    sorting character varying(100) NOT NULL,
    columns jsonb NOT NULL,
    is_default boolean NOT NULL,
    is_public boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    user_id bigint
);


ALTER TABLE public.saved_views OWNER TO postgres;

--
-- Name: saved_views_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.saved_views ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_views_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.settings (
    id bigint NOT NULL,
    key character varying(100) NOT NULL,
    value text NOT NULL,
    data_type character varying(20) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.settings OWNER TO postgres;

--
-- Name: settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    color character varying(7) NOT NULL,
    description text NOT NULL,
    entity_types jsonb NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL
);


ALTER TABLE public.tags OWNER TO postgres;

--
-- Name: tags_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(50) NOT NULL,
    description text NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.teams OWNER TO postgres;

--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_sessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_sessions (
    id bigint NOT NULL,
    session_key character varying(255) NOT NULL,
    device_info jsonb NOT NULL,
    ip_address inet NOT NULL,
    login_at timestamp with time zone NOT NULL,
    last_active timestamp with time zone NOT NULL,
    logout_at timestamp with time zone,
    is_active boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_sessions OWNER TO postgres;

--
-- Name: user_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    phone character varying(20) NOT NULL,
    avatar character varying(100),
    is_locked boolean NOT NULL,
    locked_at timestamp with time zone,
    locked_by_id bigint
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO postgres;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_teams (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    team_id bigint NOT NULL
);


ALTER TABLE public.users_teams OWNER TO postgres;

--
-- Name: users_teams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO postgres;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: workflow_definitions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.workflow_definitions (
    id bigint NOT NULL,
    entity_type character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    states jsonb NOT NULL,
    transitions jsonb NOT NULL,
    initial_state character varying(50) NOT NULL,
    final_states jsonb NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.workflow_definitions OWNER TO postgres;

--
-- Name: workflow_definitions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.workflow_definitions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.workflow_definitions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: approval_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.approval_history (id, entity_type, entity_id, entity_code, action, comments, created_at, level, user_id) FROM stdin;
\.


--
-- Data for Name: attachments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.attachments (id, entity_type, entity_id, file, filename, file_size, file_type, description, uploaded_at, uploaded_by_id) FROM stdin;
1	Customer	1	attachments/Customer/1/customers_20260128_101455.xlsx	customers_20260128_101455.xlsx	5522		Test file	2026-01-28 11:16:18.339121+07	1
\.


--
-- Data for Name: audit_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.audit_logs (id, action, entity_type, entity_id, entity_code, old_values, new_values, changed_fields, ip_address, user_agent, created_at, user_id) FROM stdin;
1	CREATE	Customer	3	TEST002	\N	{"code": "TEST002", "name": "Test Audit2", "email": "", "phone": "02222", "company_name": "Cong ty Nguyen Sang2"}	[]	127.0.0.1	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36	2026-01-28 10:52:35.417026+07	1
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add Role	7	add_role
26	Can change Role	7	change_role
27	Can delete Role	7	delete_role
28	Can view Role	7	view_role
29	Can add Permission	8	add_permission
30	Can change Permission	8	change_permission
31	Can delete Permission	8	delete_permission
32	Can view Permission	8	view_permission
33	Can add Team	9	add_team
34	Can change Team	9	change_team
35	Can delete Team	9	delete_team
36	Can view Team	9	view_team
37	Can add Setting	10	add_setting
38	Can change Setting	10	change_setting
39	Can delete Setting	10	delete_setting
40	Can view Setting	10	view_setting
41	Can add Customer	11	add_customer
42	Can change Customer	11	change_customer
43	Can delete Customer	11	delete_customer
44	Can view Customer	11	view_customer
45	Can add Export Template	12	add_exporttemplate
46	Can change Export Template	12	change_exporttemplate
47	Can delete Export Template	12	delete_exporttemplate
48	Can view Export Template	12	view_exporttemplate
49	Can add Saved View	13	add_savedview
50	Can change Saved View	13	change_savedview
51	Can delete Saved View	13	delete_savedview
52	Can view Saved View	13	view_savedview
53	Can add Import Log	14	add_importlog
54	Can change Import Log	14	change_importlog
55	Can delete Import Log	14	delete_importlog
56	Can view Import Log	14	view_importlog
57	Can add Audit Log	15	add_auditlog
58	Can change Audit Log	15	change_auditlog
59	Can delete Audit Log	15	delete_auditlog
60	Can view Audit Log	15	view_auditlog
61	Can add Attachment	16	add_attachment
62	Can change Attachment	16	change_attachment
63	Can delete Attachment	16	delete_attachment
64	Can view Attachment	16	view_attachment
65	Can add Comment	17	add_comment
66	Can change Comment	17	change_comment
67	Can delete Comment	17	delete_comment
68	Can view Comment	17	view_comment
69	Can add Comment Reaction	18	add_commentreaction
70	Can change Comment Reaction	18	change_commentreaction
71	Can delete Comment Reaction	18	delete_commentreaction
72	Can view Comment Reaction	18	view_commentreaction
73	Can add Notification	19	add_notification
74	Can change Notification	19	change_notification
75	Can delete Notification	19	delete_notification
76	Can view Notification	19	view_notification
77	Can add Approval History	20	add_approvalhistory
78	Can change Approval History	20	change_approvalhistory
79	Can delete Approval History	20	delete_approvalhistory
80	Can view Approval History	20	view_approvalhistory
81	Can add Number Sequence	21	add_numbersequence
82	Can change Number Sequence	21	change_numbersequence
83	Can delete Number Sequence	21	delete_numbersequence
84	Can view Number Sequence	21	view_numbersequence
85	Can add Tag	22	add_tag
86	Can change Tag	22	change_tag
87	Can delete Tag	22	delete_tag
88	Can view Tag	22	view_tag
89	Can add Entity Tag	23	add_entitytag
90	Can change Entity Tag	23	change_entitytag
91	Can delete Entity Tag	23	delete_entitytag
92	Can view Entity Tag	23	view_entitytag
93	Can add Workflow Definition	24	add_workflowdefinition
94	Can change Workflow Definition	24	change_workflowdefinition
95	Can delete Workflow Definition	24	delete_workflowdefinition
96	Can view Workflow Definition	24	view_workflowdefinition
97	Can add User Session	25	add_usersession
98	Can change User Session	25	change_usersession
99	Can delete User Session	25	delete_usersession
100	Can view User Session	25	view_usersession
101	Can add Password Policy	26	add_passwordpolicy
102	Can change Password Policy	26	change_passwordpolicy
103	Can delete Password Policy	26	delete_passwordpolicy
104	Can view Password Policy	26	view_passwordpolicy
105	Can add Scheduled task	27	add_schedule
106	Can change Scheduled task	27	change_schedule
107	Can delete Scheduled task	27	delete_schedule
108	Can view Scheduled task	27	view_schedule
109	Can add task	28	add_task
110	Can change task	28	change_task
111	Can delete task	28	delete_task
112	Can view task	28	view_task
113	Can add Failed task	29	add_failure
114	Can change Failed task	29	change_failure
115	Can delete Failed task	29	delete_failure
116	Can view Failed task	29	view_failure
117	Can add Successful task	30	add_success
118	Can change Successful task	30	change_success
119	Can delete Successful task	30	delete_success
120	Can view Successful task	30	view_success
121	Can add Queued task	31	add_ormq
122	Can change Queued task	31	change_ormq
123	Can delete Queued task	31	delete_ormq
124	Can view Queued task	31	view_ormq
\.


--
-- Data for Name: comment_reactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comment_reactions (id, reaction_type, created_at, comment_id, user_id) FROM stdin;
\.


--
-- Data for Name: comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comments (id, entity_type, entity_id, content, mentions, created_at, updated_at, is_deleted, deleted_at, created_by_id, parent_id) FROM stdin;
1	Customer	1	This is a test comment with @newadmin mention	["newadmin"]	2026-01-28 11:35:02.147121+07	2026-01-28 11:35:02.147131+07	f	\N	1	\N
2	Customer	1	Hello @newadmin, please check this customer!	["newadmin"]	2026-01-28 14:07:39.996991+07	2026-01-28 14:07:39.997002+07	f	\N	1	\N
3	Customer	1	Test notification for @newadmin again	["newadmin"]	2026-01-28 14:17:05.10489+07	2026-01-28 14:17:05.104898+07	f	\N	1	\N
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, code, name, company_name, tax_code, phone, email, address, contact_person, contact_phone, payment_terms, credit_limit, is_active, created_at, updated_at, created_by_id, updated_by_id, approved_at, approved_by_id, rejected_at, rejected_by_id, rejection_reason, status, owner_id, team_id) FROM stdin;
1	ABC	NGUYỄN THÀNH	Cong ty A	032222	0919046246	danghong25081998@gmail.com	104D đường 628, Trại Đèn, Phước Hiệp, Củ Chi	NGUYỄN THÀNH		30	0.00	t	2026-01-27 15:23:18.606422+07	2026-01-27 15:23:18.606445+07	\N	\N	\N	\N	\N	\N		DRAFT	\N	\N
2	TEST001	Test Audit	Test Audit Updated	0312444	0123546		Cu Chi	Son		30	0.00	t	2026-01-28 10:29:10.214322+07	2026-01-28 10:37:14.45765+07	\N	\N	\N	\N	\N	\N		DRAFT	\N	\N
3	TEST002	Test Audit2	Cong ty Nguyen Sang2	2222	02222		cu chi			30	0.00	t	2026-01-28 10:52:35.409677+07	2026-01-28 10:52:35.409687+07	\N	\N	\N	\N	\N	\N		DRAFT	\N	\N
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-01-27 15:23:18.624046+07	1	ABC - NGUYỄN THÀNH	1	[{"added": {}}]	11	1
2	2026-01-28 10:29:10.222075+07	2	NTT - Nguyen Sang	1	[{"added": {}}]	11	1
3	2026-01-28 10:37:14.462784+07	2	TEST001 - Test Audit	2	[{"changed": {"fields": ["Code", "Name", "Company name"]}}]	11	1
4	2026-01-28 10:52:35.423452+07	3	TEST002 - Test Audit2	1	[{"added": {}}]	11	1
5	2026-01-28 11:16:18.351453+07	1	customers_20260128_101455.xlsx (Customer #1)	1	[{"added": {}}]	16	1
6	2026-01-28 11:35:02.157049+07	1	newadmin: This is a test comment with @newadmin mention	1	[{"added": {}}]	17	1
7	2026-01-28 13:56:40.652727+07	1	Sản Xuat	1	[{"added": {}}]	9	1
8	2026-01-28 14:07:40.019654+07	2	newadmin: Hello @newadmin, please check this customer!	1	[{"added": {}}]	17	1
9	2026-01-28 14:17:05.112327+07	3	newadmin: Test notification for @newadmin again	1	[{"added": {}}]	17	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	core	user
7	core	role
8	core	permission
9	core	team
10	core	setting
11	core	customer
12	core	exporttemplate
13	core	savedview
14	core	importlog
15	core	auditlog
16	core	attachment
17	core	comment
18	core	commentreaction
19	core	notification
20	core	approvalhistory
21	core	numbersequence
22	core	tag
23	core	entitytag
24	core	workflowdefinition
25	core	usersession
26	core	passwordpolicy
27	django_q	schedule
28	django_q	task
29	django_q	failure
30	django_q	success
31	django_q	ormq
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-01-24 13:49:22.431776+07
2	contenttypes	0002_remove_content_type_name	2026-01-24 13:49:22.442555+07
3	auth	0001_initial	2026-01-24 13:49:22.478493+07
4	auth	0002_alter_permission_name_max_length	2026-01-24 13:49:22.482809+07
5	auth	0003_alter_user_email_max_length	2026-01-24 13:49:22.485763+07
6	auth	0004_alter_user_username_opts	2026-01-24 13:49:22.489815+07
7	auth	0005_alter_user_last_login_null	2026-01-24 13:49:22.496198+07
8	auth	0006_require_contenttypes_0002	2026-01-24 13:49:22.497881+07
9	auth	0007_alter_validators_add_error_messages	2026-01-24 13:49:22.500838+07
10	auth	0008_alter_user_username_max_length	2026-01-24 13:49:22.504249+07
11	auth	0009_alter_user_last_name_max_length	2026-01-24 13:49:22.508778+07
12	auth	0010_alter_group_name_max_length	2026-01-24 13:49:22.51684+07
13	auth	0011_update_proxy_permissions	2026-01-24 13:49:22.520084+07
14	auth	0012_alter_user_first_name_max_length	2026-01-24 13:49:22.524739+07
15	core	0001_initial	2026-01-24 13:49:22.57026+07
16	admin	0001_initial	2026-01-24 13:49:22.58547+07
17	admin	0002_logentry_remove_auto_add	2026-01-24 13:49:22.590119+07
18	admin	0003_logentry_add_action_flag_choices	2026-01-24 13:49:22.593893+07
19	sessions	0001_initial	2026-01-24 13:49:22.60121+07
20	core	0002_role	2026-01-24 14:09:27.935442+07
21	core	0003_permission	2026-01-24 14:48:56.319981+07
22	core	0004_role_permissions	2026-01-24 15:11:57.940343+07
24	core	0005_alter_user_options_alter_user_table	2026-01-24 15:44:02.822209+07
25	core	0006_alter_user_options_user_roles_alter_role_created_at_and_more	2026-01-24 15:50:40.804971+07
26	core	0007_team	2026-01-26 14:28:50.840485+07
27	core	0008_user_teams	2026-01-26 14:37:55.75248+07
28	core	0009_setting	2026-01-26 14:41:30.203749+07
29	core	0010_customer	2026-01-26 18:24:55.395986+07
30	core	0011_exporttemplate	2026-01-27 10:02:35.310532+07
31	core	0012_savedview	2026-01-27 15:42:21.669214+07
32	core	0013_importlog	2026-01-28 09:53:40.142055+07
33	core	0014_auditlog	2026-01-28 10:20:10.135864+07
34	core	0015_attachment	2026-01-28 11:01:28.798356+07
35	core	0016_comment	2026-01-28 11:25:48.090616+07
36	core	0017_commentreaction	2026-01-28 12:43:11.45916+07
37	core	0018_notification	2026-01-28 12:49:35.719658+07
38	core	0019_customer_approved_at_customer_approved_by_and_more	2026-01-28 14:23:46.243468+07
39	core	0020_approvalhistory	2026-01-28 14:39:18.057+07
40	core	0021_numbersequence	2026-01-28 14:59:12.571308+07
41	core	0022_tag_entitytag	2026-01-28 15:07:14.074425+07
42	core	0023_customer_owner_customer_team	2026-01-28 15:34:27.212252+07
43	core	0024_workflowdefinition	2026-01-28 15:44:44.201842+07
44	core	0025_usersession	2026-01-28 15:50:23.46246+07
45	core	0026_passwordpolicy	2026-01-28 16:12:19.619868+07
46	django_q	0001_initial	2026-01-28 16:34:34.309647+07
47	django_q	0002_auto_20150630_1624	2026-01-28 16:34:34.324841+07
48	django_q	0003_auto_20150708_1326	2026-01-28 16:34:34.358599+07
49	django_q	0004_auto_20150710_1043	2026-01-28 16:34:34.363658+07
50	django_q	0005_auto_20150718_1506	2026-01-28 16:34:34.372175+07
51	django_q	0006_auto_20150805_1817	2026-01-28 16:34:34.378285+07
52	django_q	0007_ormq	2026-01-28 16:34:34.389763+07
53	django_q	0008_auto_20160224_1026	2026-01-28 16:34:34.392289+07
54	django_q	0009_auto_20171009_0915	2026-01-28 16:34:34.404104+07
55	django_q	0010_auto_20200610_0856	2026-01-28 16:34:34.411568+07
56	django_q	0011_auto_20200628_1055	2026-01-28 16:34:34.415626+07
57	django_q	0012_auto_20200702_1608	2026-01-28 16:34:34.417712+07
58	django_q	0013_task_attempt_count	2026-01-28 16:34:34.422515+07
59	django_q	0014_schedule_cluster	2026-01-28 16:34:34.42478+07
60	django_q	0015_alter_schedule_schedule_type	2026-01-28 16:34:34.428402+07
61	django_q	0016_schedule_intended_date_kwarg	2026-01-28 16:34:34.433225+07
62	django_q	0017_task_cluster_alter	2026-01-28 16:34:34.4398+07
63	django_q	0018_task_success_index	2026-01-28 16:34:34.44496+07
\.


--
-- Data for Name: django_q_ormq; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_q_ormq (id, key, payload, lock) FROM stdin;
\.


--
-- Data for Name: django_q_schedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_q_schedule (id, func, hook, args, kwargs, schedule_type, repeats, next_run, task, name, minutes, cron, cluster, intended_date_kwarg) FROM stdin;
\.


--
-- Data for Name: django_q_task; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_q_task (name, func, hook, args, kwargs, result, started, stopped, success, id, "group", attempt_count, cluster) FROM stdin;
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
g7sev72ktbm7d11bj8pz23a0jvvesbwg	.eJxVjM0OwiAQhN-FsyH81IV69O4zEGB3pWogKe3J-O62SQ96m8z3zbxFiOtSwtppDhOKi9Di9NulmJ9Ud4CPWO9N5laXeUpyV-RBu7w1pNf1cP8OSuxlW3uKPGilQTMYy4QGAJNyYLM_W_RuS04zETiTNCkzkPLskRlHGCOLzxfW0jfr:1vkeK2:HYm0yM0BEYvSIBcrBliNZam53HyB7G1Ehddk6nzuj8w	2026-02-10 15:21:14.852113+07
\.


--
-- Data for Name: entity_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.entity_tags (id, entity_type, entity_id, created_at, created_by_id, tag_id) FROM stdin;
\.


--
-- Data for Name: export_templates; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.export_templates (id, name, entity_type, columns, headers, is_default, is_active, created_at, updated_at, created_by_id) FROM stdin;
1	Customer - Full	Customer	["code", "name", "company_name", "tax_code", "phone", "email", "address", "contact_person", "contact_phone", "payment_terms", "credit_limit", "is_active", "created_at"]	["Mã KH", "Tên KH", "Tên công ty", "MST", "Điện thoại", "Email", "Địa chỉ", "Người liên hệ", "SĐT liên hệ", "Thời hạn TT", "Hạn mức", "Trạng thái", "Ngày tạo"]	t	t	2026-01-27 14:52:17.749374+07	2026-01-27 14:52:17.749391+07	\N
\.


--
-- Data for Name: import_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.import_logs (id, entity_type, filename, total_rows, success_count, error_count, errors, status, created_at, created_by_id) FROM stdin;
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, notification_type, title, message, entity_type, entity_id, is_read, read_at, created_at, actor_id, recipient_id) FROM stdin;
\.


--
-- Data for Name: number_sequences; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.number_sequences (id, entity_type, prefix, current_number, padding, format_template, is_active) FROM stdin;
3	Invoice	INV	0	4	{prefix}-{YYYY}{MM}-{number}	t
1	Customer	CUST	2	3	{prefix}-{number}	t
2	SalesOrder	SO	1	4	{prefix}-{YYYY}-{number}	t
\.


--
-- Data for Name: password_policies; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.password_policies (id, name, min_length, require_uppercase, require_lowercase, require_digit, require_special, prevent_reuse_count, expire_days, force_change_first_login, is_active) FROM stdin;
1	Default Policy	8	t	t	t	f	3	90	t	t
\.


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.permissions (id, name, code, resource, action, description, created_at) FROM stdin;
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, name, code, description, is_active, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: roles_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles_permissions (id, role_id, permission_id) FROM stdin;
\.


--
-- Data for Name: saved_views; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.saved_views (id, name, entity_type, filters, sorting, columns, is_default, is_public, created_at, updated_at, created_by_id, user_id) FROM stdin;
\.


--
-- Data for Name: settings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.settings (id, key, value, data_type, description, is_active, created_at, updated_at) FROM stdin;
1	company_name	Công ty TNHH Carton Box	string	Tên công ty	t	2026-01-28 14:56:28.86788+07	2026-01-28 14:56:28.867896+07
2	company_address	123 Đường ABC, Quận 1, TP.HCM	string	Địa chỉ công ty	t	2026-01-28 14:56:28.880099+07	2026-01-28 14:56:28.880112+07
3	company_phone	028-1234-5678	string	Số điện thoại	t	2026-01-28 14:56:28.881408+07	2026-01-28 14:56:28.881417+07
4	company_email	info@cartonbox.com	string	Email công ty	t	2026-01-28 14:56:28.882961+07	2026-01-28 14:56:28.882971+07
\.


--
-- Data for Name: tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tags (id, name, color, description, entity_types, is_active, created_at) FROM stdin;
1	VIP	#FFD700	VIP customer	["Customer"]	t	2026-01-28 15:09:17.569374+07
2	Hot	#FF4500	Hot lead	["Customer"]	t	2026-01-28 15:09:17.591947+07
3	Urgent	#DC2626	Urgent order	["SalesOrder", "Invoice"]	t	2026-01-28 15:09:17.593108+07
4	On Hold	#F59E0B	On hold	["Customer", "SalesOrder"]	t	2026-01-28 15:09:17.593853+07
\.


--
-- Data for Name: teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teams (id, name, code, description, is_active, created_at, updated_at) FROM stdin;
1	Sản Xuat	SX	Dung cho sản xuất	t	2026-01-28 13:56:40.640534+07	2026-01-28 13:56:40.640544+07
\.


--
-- Data for Name: user_sessions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_sessions (id, session_key, device_info, ip_address, login_at, last_active, logout_at, is_active, user_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, phone, avatar, is_locked, locked_at, locked_by_id) FROM stdin;
1	pbkdf2_sha256$720000$uBAXmQQ6YK2tnyLlHDFV74$KkHbSBzsSkS9IufFr6j8b+8YrI/8tk/llvORn7EZksE=	2026-01-27 15:21:14.84728+07	t	newadmin				t	t	2026-01-27 15:19:06.000209+07			f	\N	\N
\.


--
-- Data for Name: users_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: users_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_roles (id, user_id, role_id) FROM stdin;
\.


--
-- Data for Name: users_teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_teams (id, user_id, team_id) FROM stdin;
\.


--
-- Data for Name: users_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: workflow_definitions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.workflow_definitions (id, entity_type, name, description, states, transitions, initial_state, final_states, is_active, created_at, updated_at) FROM stdin;
1	Customer	Customer Approval	Simple customer approval workflow	[{"code": "DRAFT", "name": "Draft", "color": "#6B7280"}, {"code": "PENDING_APPROVAL", "name": "Pending Approval", "color": "#F59E0B"}, {"code": "APPROVED", "name": "Approved", "color": "#10B981"}, {"code": "REJECTED", "name": "Rejected", "color": "#EF4444"}]	[{"to": "PENDING_APPROVAL", "from": "DRAFT", "action": "submit", "required_permission": null}, {"to": "APPROVED", "from": "PENDING_APPROVAL", "action": "approve", "required_permission": "core.customer.approve"}, {"to": "REJECTED", "from": "PENDING_APPROVAL", "action": "reject", "required_permission": "core.customer.approve"}, {"to": "DRAFT", "from": "REJECTED", "action": "reopen", "required_permission": null}]	DRAFT	["APPROVED", "REJECTED"]	t	2026-01-28 15:47:40.182739+07	2026-01-28 15:47:40.182758+07
2	SalesOrder	Sales Order Processing	Complete sales order workflow	[{"code": "DRAFT", "name": "Draft", "color": "#6B7280"}, {"code": "PENDING", "name": "Pending Review", "color": "#3B82F6"}, {"code": "APPROVED", "name": "Approved", "color": "#10B981"}, {"code": "IN_PROGRESS", "name": "In Progress", "color": "#8B5CF6"}, {"code": "COMPLETED", "name": "Completed", "color": "#059669"}, {"code": "CANCELLED", "name": "Cancelled", "color": "#EF4444"}]	[{"to": "PENDING", "from": "DRAFT", "action": "submit", "required_permission": null}, {"to": "APPROVED", "from": "PENDING", "action": "approve", "required_permission": "sales.order.approve"}, {"to": "DRAFT", "from": "PENDING", "action": "return", "required_permission": "sales.order.approve"}, {"to": "IN_PROGRESS", "from": "APPROVED", "action": "start", "required_permission": null}, {"to": "COMPLETED", "from": "IN_PROGRESS", "action": "complete", "required_permission": null}, {"to": "CANCELLED", "from": "DRAFT", "action": "cancel", "required_permission": null}, {"to": "CANCELLED", "from": "PENDING", "action": "cancel", "required_permission": "sales.order.approve"}]	DRAFT	["COMPLETED", "CANCELLED"]	t	2026-01-28 15:47:40.210613+07	2026-01-28 15:47:40.210622+07
\.


--
-- Name: approval_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.approval_history_id_seq', 1, false);


--
-- Name: attachments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.attachments_id_seq', 1, true);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.audit_logs_id_seq', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 124, true);


--
-- Name: comment_reactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comment_reactions_id_seq', 1, false);


--
-- Name: comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comments_id_seq', 3, true);


--
-- Name: core_user_roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.core_user_roles_id_seq', 1, false);


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 9, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 31, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 63, true);


--
-- Name: django_q_ormq_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_q_ormq_id_seq', 1, false);


--
-- Name: django_q_schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_q_schedule_id_seq', 1, false);


--
-- Name: entity_tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.entity_tags_id_seq', 1, false);


--
-- Name: export_templates_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.export_templates_id_seq', 2, true);


--
-- Name: import_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.import_logs_id_seq', 1, false);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 1, false);


--
-- Name: number_sequences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.number_sequences_id_seq', 3, true);


--
-- Name: password_policies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.password_policies_id_seq', 1, true);


--
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permissions_id_seq', 1, false);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 1, false);


--
-- Name: roles_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_permissions_id_seq', 1, false);


--
-- Name: saved_views_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.saved_views_id_seq', 1, false);


--
-- Name: settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.settings_id_seq', 4, true);


--
-- Name: tags_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tags_id_seq', 4, true);


--
-- Name: teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teams_id_seq', 1, true);


--
-- Name: user_sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_sessions_id_seq', 1, false);


--
-- Name: users_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_groups_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, true);


--
-- Name: users_teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_teams_id_seq', 1, false);


--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_permissions_id_seq', 1, false);


--
-- Name: workflow_definitions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.workflow_definitions_id_seq', 2, true);


--
-- Name: approval_history approval_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approval_history
    ADD CONSTRAINT approval_history_pkey PRIMARY KEY (id);


--
-- Name: attachments attachments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: comment_reactions comment_reactions_comment_id_user_id_4e08c344_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_reactions
    ADD CONSTRAINT comment_reactions_comment_id_user_id_4e08c344_uniq UNIQUE (comment_id, user_id);


--
-- Name: comment_reactions comment_reactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_reactions
    ADD CONSTRAINT comment_reactions_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: users_roles core_user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT core_user_roles_pkey PRIMARY KEY (id);


--
-- Name: customers customers_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_code_key UNIQUE (code);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_q_ormq django_q_ormq_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_q_ormq
    ADD CONSTRAINT django_q_ormq_pkey PRIMARY KEY (id);


--
-- Name: django_q_schedule django_q_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_q_schedule
    ADD CONSTRAINT django_q_schedule_pkey PRIMARY KEY (id);


--
-- Name: django_q_task django_q_task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_q_task
    ADD CONSTRAINT django_q_task_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: entity_tags entity_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entity_tags
    ADD CONSTRAINT entity_tags_pkey PRIMARY KEY (id);


--
-- Name: entity_tags entity_tags_tag_id_entity_type_entity_id_da6c2b1f_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entity_tags
    ADD CONSTRAINT entity_tags_tag_id_entity_type_entity_id_da6c2b1f_uniq UNIQUE (tag_id, entity_type, entity_id);


--
-- Name: export_templates export_templates_entity_type_name_bef14534_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.export_templates
    ADD CONSTRAINT export_templates_entity_type_name_bef14534_uniq UNIQUE (entity_type, name);


--
-- Name: export_templates export_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.export_templates
    ADD CONSTRAINT export_templates_pkey PRIMARY KEY (id);


--
-- Name: import_logs import_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.import_logs
    ADD CONSTRAINT import_logs_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: number_sequences number_sequences_entity_type_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.number_sequences
    ADD CONSTRAINT number_sequences_entity_type_key UNIQUE (entity_type);


--
-- Name: number_sequences number_sequences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.number_sequences
    ADD CONSTRAINT number_sequences_pkey PRIMARY KEY (id);


--
-- Name: password_policies password_policies_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_policies
    ADD CONSTRAINT password_policies_name_key UNIQUE (name);


--
-- Name: password_policies password_policies_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.password_policies
    ADD CONSTRAINT password_policies_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_code_key UNIQUE (code);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id);


--
-- Name: permissions permissions_resource_action_6a6bc759_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_resource_action_6a6bc759_uniq UNIQUE (resource, action);


--
-- Name: roles roles_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_code_key UNIQUE (code);


--
-- Name: roles roles_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_name_key UNIQUE (name);


--
-- Name: roles_permissions roles_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles_permissions
    ADD CONSTRAINT roles_permissions_pkey PRIMARY KEY (id);


--
-- Name: roles_permissions roles_permissions_role_id_permission_id_d2305313_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles_permissions
    ADD CONSTRAINT roles_permissions_role_id_permission_id_d2305313_uniq UNIQUE (role_id, permission_id);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: saved_views saved_views_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_views
    ADD CONSTRAINT saved_views_pkey PRIMARY KEY (id);


--
-- Name: saved_views saved_views_user_id_entity_type_name_385a3cf5_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_views
    ADD CONSTRAINT saved_views_user_id_entity_type_name_385a3cf5_uniq UNIQUE (user_id, entity_type, name);


--
-- Name: settings settings_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_key_key UNIQUE (key);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (id);


--
-- Name: tags tags_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_name_key UNIQUE (name);


--
-- Name: tags tags_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (id);


--
-- Name: teams teams_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_code_key UNIQUE (code);


--
-- Name: teams teams_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_name_key UNIQUE (name);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: user_sessions user_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_pkey PRIMARY KEY (id);


--
-- Name: user_sessions user_sessions_session_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_session_key_key UNIQUE (session_key);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_roles users_roles_user_id_role_id_afea9d03_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_user_id_role_id_afea9d03_uniq UNIQUE (user_id, role_id);


--
-- Name: users_teams users_teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_teams
    ADD CONSTRAINT users_teams_pkey PRIMARY KEY (id);


--
-- Name: users_teams users_teams_user_id_team_id_c59c1da6_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_teams
    ADD CONSTRAINT users_teams_user_id_team_id_c59c1da6_uniq UNIQUE (user_id, team_id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: workflow_definitions workflow_definitions_entity_type_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_definitions
    ADD CONSTRAINT workflow_definitions_entity_type_key UNIQUE (entity_type);


--
-- Name: workflow_definitions workflow_definitions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.workflow_definitions
    ADD CONSTRAINT workflow_definitions_pkey PRIMARY KEY (id);


--
-- Name: approval_hi_entity__254ce6_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX approval_hi_entity__254ce6_idx ON public.approval_history USING btree (entity_type, entity_id);


--
-- Name: approval_hi_user_id_ba75ab_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX approval_hi_user_id_ba75ab_idx ON public.approval_history USING btree (user_id, created_at);


--
-- Name: approval_history_user_id_2fac6050; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX approval_history_user_id_2fac6050 ON public.approval_history USING btree (user_id);


--
-- Name: attachments_entity__d756e0_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX attachments_entity__d756e0_idx ON public.attachments USING btree (entity_type, entity_id);


--
-- Name: attachments_uploaded_by_id_ffd2878c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX attachments_uploaded_by_id_ffd2878c ON public.attachments USING btree (uploaded_by_id);


--
-- Name: audit_logs_action_391715_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_logs_action_391715_idx ON public.audit_logs USING btree (action, created_at);


--
-- Name: audit_logs_entity__d4c2e5_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_logs_entity__d4c2e5_idx ON public.audit_logs USING btree (entity_type, entity_id);


--
-- Name: audit_logs_user_id_752b0e2b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_logs_user_id_752b0e2b ON public.audit_logs USING btree (user_id);


--
-- Name: audit_logs_user_id_fbfd51_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX audit_logs_user_id_fbfd51_idx ON public.audit_logs USING btree (user_id, created_at);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: comment_reactions_comment_id_87c59446; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX comment_reactions_comment_id_87c59446 ON public.comment_reactions USING btree (comment_id);


--
-- Name: comment_reactions_user_id_de8dbdab; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX comment_reactions_user_id_de8dbdab ON public.comment_reactions USING btree (user_id);


--
-- Name: comments_created_971cde_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX comments_created_971cde_idx ON public.comments USING btree (created_by_id, created_at);


--
-- Name: comments_created_by_id_33e10326; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX comments_created_by_id_33e10326 ON public.comments USING btree (created_by_id);


--
-- Name: comments_entity__ecb426_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX comments_entity__ecb426_idx ON public.comments USING btree (entity_type, entity_id);


--
-- Name: comments_parent_id_d317363b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX comments_parent_id_d317363b ON public.comments USING btree (parent_id);


--
-- Name: customers_approved_by_id_9d464637; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_approved_by_id_9d464637 ON public.customers USING btree (approved_by_id);


--
-- Name: customers_code_bb32c51d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_code_bb32c51d_like ON public.customers USING btree (code varchar_pattern_ops);


--
-- Name: customers_created_by_id_3d0160f2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_created_by_id_3d0160f2 ON public.customers USING btree (created_by_id);


--
-- Name: customers_owner_id_ce32fefc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_owner_id_ce32fefc ON public.customers USING btree (owner_id);


--
-- Name: customers_rejected_by_id_0f790bb6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_rejected_by_id_0f790bb6 ON public.customers USING btree (rejected_by_id);


--
-- Name: customers_team_id_a79b65c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_team_id_a79b65c2 ON public.customers USING btree (team_id);


--
-- Name: customers_updated_by_id_62864352; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX customers_updated_by_id_62864352 ON public.customers USING btree (updated_by_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_q_task_id_32882367_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_q_task_id_32882367_like ON public.django_q_task USING btree (id varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: entity_tags_created_by_id_53367d70; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX entity_tags_created_by_id_53367d70 ON public.entity_tags USING btree (created_by_id);


--
-- Name: entity_tags_entity__561e74_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX entity_tags_entity__561e74_idx ON public.entity_tags USING btree (entity_type, entity_id);


--
-- Name: entity_tags_tag_id_fe750108; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX entity_tags_tag_id_fe750108 ON public.entity_tags USING btree (tag_id);


--
-- Name: export_templates_created_by_id_b271df0c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX export_templates_created_by_id_b271df0c ON public.export_templates USING btree (created_by_id);


--
-- Name: import_logs_created_by_id_5a65dd9a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX import_logs_created_by_id_5a65dd9a ON public.import_logs USING btree (created_by_id);


--
-- Name: notificatio_recipie_06c470_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notificatio_recipie_06c470_idx ON public.notifications USING btree (recipient_id, is_read, created_at);


--
-- Name: notifications_actor_id_f6ddf1d3; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notifications_actor_id_f6ddf1d3 ON public.notifications USING btree (actor_id);


--
-- Name: notifications_recipient_id_e1133bac; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX notifications_recipient_id_e1133bac ON public.notifications USING btree (recipient_id);


--
-- Name: number_sequences_entity_type_90638938_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX number_sequences_entity_type_90638938_like ON public.number_sequences USING btree (entity_type varchar_pattern_ops);


--
-- Name: password_policies_name_68571063_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX password_policies_name_68571063_like ON public.password_policies USING btree (name varchar_pattern_ops);


--
-- Name: permissions_code_c5331a5c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX permissions_code_c5331a5c_like ON public.permissions USING btree (code varchar_pattern_ops);


--
-- Name: roles_code_e726c310_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX roles_code_e726c310_like ON public.roles USING btree (code varchar_pattern_ops);


--
-- Name: roles_name_51259447_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX roles_name_51259447_like ON public.roles USING btree (name varchar_pattern_ops);


--
-- Name: roles_permissions_permission_id_1f74cd91; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX roles_permissions_permission_id_1f74cd91 ON public.roles_permissions USING btree (permission_id);


--
-- Name: roles_permissions_role_id_e913de52; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX roles_permissions_role_id_e913de52 ON public.roles_permissions USING btree (role_id);


--
-- Name: saved_views_created_by_id_5079cf68; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX saved_views_created_by_id_5079cf68 ON public.saved_views USING btree (created_by_id);


--
-- Name: saved_views_user_id_290300cc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX saved_views_user_id_290300cc ON public.saved_views USING btree (user_id);


--
-- Name: settings_key_f16b5bae_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX settings_key_f16b5bae_like ON public.settings USING btree (key varchar_pattern_ops);


--
-- Name: success_index; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX success_index ON public.django_q_task USING btree ("group", name, func) WHERE success;


--
-- Name: tags_name_d06e0d9e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tags_name_d06e0d9e_like ON public.tags USING btree (name varchar_pattern_ops);


--
-- Name: teams_code_019919d8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX teams_code_019919d8_like ON public.teams USING btree (code varchar_pattern_ops);


--
-- Name: teams_name_bd7d028e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX teams_name_bd7d028e_like ON public.teams USING btree (name varchar_pattern_ops);


--
-- Name: user_sessio_user_id_bb1b83_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_sessio_user_id_bb1b83_idx ON public.user_sessions USING btree (user_id, is_active);


--
-- Name: user_sessions_session_key_5c5616a8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_sessions_session_key_5c5616a8_like ON public.user_sessions USING btree (session_key varchar_pattern_ops);


--
-- Name: user_sessions_user_id_43ce9642; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX user_sessions_user_id_43ce9642 ON public.user_sessions USING btree (user_id);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_locked_by_id_6749ba95; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_locked_by_id_6749ba95 ON public.users USING btree (locked_by_id);


--
-- Name: users_roles_role_id_fe00bf26; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_roles_role_id_fe00bf26 ON public.users_roles USING btree (role_id);


--
-- Name: users_roles_user_id_a7500f73; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_roles_user_id_a7500f73 ON public.users_roles USING btree (user_id);


--
-- Name: users_teams_team_id_919d3593; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_teams_team_id_919d3593 ON public.users_teams USING btree (team_id);


--
-- Name: users_teams_user_id_8ecf8098; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_teams_user_id_8ecf8098 ON public.users_teams USING btree (user_id);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: workflow_definitions_entity_type_89da6745_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX workflow_definitions_entity_type_89da6745_like ON public.workflow_definitions USING btree (entity_type varchar_pattern_ops);


--
-- Name: approval_history approval_history_user_id_2fac6050_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.approval_history
    ADD CONSTRAINT approval_history_user_id_2fac6050_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: attachments attachments_uploaded_by_id_ffd2878c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.attachments
    ADD CONSTRAINT attachments_uploaded_by_id_ffd2878c_fk_users_id FOREIGN KEY (uploaded_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: audit_logs audit_logs_user_id_752b0e2b_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_user_id_752b0e2b_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comment_reactions comment_reactions_comment_id_87c59446_fk_comments_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_reactions
    ADD CONSTRAINT comment_reactions_comment_id_87c59446_fk_comments_id FOREIGN KEY (comment_id) REFERENCES public.comments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comment_reactions comment_reactions_user_id_de8dbdab_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comment_reactions
    ADD CONSTRAINT comment_reactions_user_id_de8dbdab_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comments comments_created_by_id_33e10326_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_created_by_id_33e10326_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: comments comments_parent_id_d317363b_fk_comments_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_parent_id_d317363b_fk_comments_id FOREIGN KEY (parent_id) REFERENCES public.comments(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customers customers_approved_by_id_9d464637_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_approved_by_id_9d464637_fk_users_id FOREIGN KEY (approved_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customers customers_created_by_id_3d0160f2_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_created_by_id_3d0160f2_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customers customers_owner_id_ce32fefc_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_owner_id_ce32fefc_fk_users_id FOREIGN KEY (owner_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customers customers_rejected_by_id_0f790bb6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_rejected_by_id_0f790bb6_fk_users_id FOREIGN KEY (rejected_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customers customers_team_id_a79b65c2_fk_teams_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_team_id_a79b65c2_fk_teams_id FOREIGN KEY (team_id) REFERENCES public.teams(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: customers customers_updated_by_id_62864352_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_updated_by_id_62864352_fk_users_id FOREIGN KEY (updated_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entity_tags entity_tags_created_by_id_53367d70_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entity_tags
    ADD CONSTRAINT entity_tags_created_by_id_53367d70_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: entity_tags entity_tags_tag_id_fe750108_fk_tags_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.entity_tags
    ADD CONSTRAINT entity_tags_tag_id_fe750108_fk_tags_id FOREIGN KEY (tag_id) REFERENCES public.tags(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: export_templates export_templates_created_by_id_b271df0c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.export_templates
    ADD CONSTRAINT export_templates_created_by_id_b271df0c_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: import_logs import_logs_created_by_id_5a65dd9a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.import_logs
    ADD CONSTRAINT import_logs_created_by_id_5a65dd9a_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications notifications_actor_id_f6ddf1d3_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_actor_id_f6ddf1d3_fk_users_id FOREIGN KEY (actor_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: notifications notifications_recipient_id_e1133bac_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_recipient_id_e1133bac_fk_users_id FOREIGN KEY (recipient_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: roles_permissions roles_permissions_permission_id_1f74cd91_fk_permissions_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles_permissions
    ADD CONSTRAINT roles_permissions_permission_id_1f74cd91_fk_permissions_id FOREIGN KEY (permission_id) REFERENCES public.permissions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: roles_permissions roles_permissions_role_id_e913de52_fk_roles_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles_permissions
    ADD CONSTRAINT roles_permissions_role_id_e913de52_fk_roles_id FOREIGN KEY (role_id) REFERENCES public.roles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: saved_views saved_views_created_by_id_5079cf68_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_views
    ADD CONSTRAINT saved_views_created_by_id_5079cf68_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: saved_views saved_views_user_id_290300cc_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.saved_views
    ADD CONSTRAINT saved_views_user_id_290300cc_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_sessions user_sessions_user_id_43ce9642_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_sessions
    ADD CONSTRAINT user_sessions_user_id_43ce9642_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users users_locked_by_id_6749ba95_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_locked_by_id_6749ba95_fk_users_id FOREIGN KEY (locked_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_roles users_roles_role_id_fe00bf26_fk_roles_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_role_id_fe00bf26_fk_roles_id FOREIGN KEY (role_id) REFERENCES public.roles(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_roles users_roles_user_id_a7500f73_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_roles
    ADD CONSTRAINT users_roles_user_id_a7500f73_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_teams users_teams_team_id_919d3593_fk_teams_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_teams
    ADD CONSTRAINT users_teams_team_id_919d3593_fk_teams_id FOREIGN KEY (team_id) REFERENCES public.teams(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_teams users_teams_user_id_8ecf8098_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_teams
    ADD CONSTRAINT users_teams_user_id_8ecf8098_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 6VMzZpnrkhW7oTr2PfqTcHPWudhEdqCPWbH7uej6fstAYamGRxEWIZz83RIJtJo

