# Generated by Django 6.0.2 on 2026-03-13 12:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_seed_production_permissions'),
        ('finance', '0004_rename_finance_adv_settle_6bb21f_idx_finance_adv_settlem_7dc2e8_idx_and_more'),
        ('purchasing', '0001_initial'),
        ('sales', '0005_salesorderdeliveryplan_shipped_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(blank=True, default='')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã phải trả')),
                ('supplier_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot nhà cung cấp')),
                ('document_date', models.DateField(verbose_name='Ngày ghi nhận')),
                ('due_date', models.DateField(verbose_name='Ngày đến hạn')),
                ('vendor_invoice_no', models.CharField(blank=True, default='', max_length=100, verbose_name='Số hóa đơn NCC')),
                ('vendor_invoice_date', models.DateField(blank=True, null=True, verbose_name='Ngày hóa đơn NCC')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Tiền tệ')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, verbose_name='Tỷ giá')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tiền hàng')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thuế')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng phải trả')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Đã chi')),
                ('status', models.CharField(choices=[('OPEN', 'Chưa chi'), ('PARTIAL', 'Chi một phần'), ('SETTLED', 'Đã chi đủ'), ('CANCELLED', 'Đã hủy')], default='OPEN', max_length=20, verbose_name='Trạng thái')),
                ('reference', models.CharField(blank=True, default='', max_length=200, verbose_name='Tham chiếu')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payables_created', to=settings.AUTH_USER_MODEL)),
                ('source_purchase_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_document', to='purchasing.purchasereceipt', verbose_name='Phiếu nhập nguồn')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_documents', to='purchasing.supplier', verbose_name='Nhà cung cấp')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payables_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_payable_documents',
                'ordering': ['due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PayableSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(blank=True, default='')),
                ('settlement_date', models.DateField(verbose_name='Ngày thanh toán')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền chi')),
                ('source_type', models.CharField(choices=[('CASH', 'Tiền mặt / Quỹ'), ('BANK', 'Ngân hàng')], default='CASH', max_length=20, verbose_name='Nguồn tiền')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_settlement', to='finance.cashtransaction', verbose_name='Giao dịch quỹ/ngân hàng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payable_settlements_created', to=settings.AUTH_USER_MODEL)),
                ('payable_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='finance.payabledocument', verbose_name='Chứng từ phải trả')),
                ('source_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_settlements_from_bank', to='finance.bankaccount', verbose_name='Ngân hàng chi')),
                ('source_cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_settlements_from_cash', to='finance.cashaccount', verbose_name='Quỹ chi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payable_settlements_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_payable_settlements',
                'ordering': ['-settlement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(blank=True, default='')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Mã phải thu')),
                ('customer_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot khách hàng')),
                ('document_date', models.DateField(verbose_name='Ngày ghi nhận')),
                ('due_date', models.DateField(verbose_name='Ngày đến hạn')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Tiền tệ')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, verbose_name='Tỷ giá')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tiền hàng')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Thuế')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng phải thu')),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Đã thu')),
                ('status', models.CharField(choices=[('OPEN', 'Chưa thu'), ('PARTIAL', 'Thu một phần'), ('SETTLED', 'Đã thu đủ'), ('CANCELLED', 'Đã hủy')], default='OPEN', max_length=20, verbose_name='Trạng thái')),
                ('reference', models.CharField(blank=True, default='', max_length=200, verbose_name='Tham chiếu')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_receivables_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_documents', to='core.customer', verbose_name='Khách hàng')),
                ('source_sales_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_document', to='sales.salesorder', verbose_name='Đơn bán nguồn')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_receivables_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_receivable_documents',
                'ordering': ['due_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReceivableSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(blank=True, default='')),
                ('settlement_date', models.DateField(verbose_name='Ngày thu tiền')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền thu')),
                ('source_type', models.CharField(choices=[('CASH', 'Tiền mặt / Quỹ'), ('BANK', 'Ngân hàng')], default='CASH', max_length=20, verbose_name='Nguồn tiền')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_settlement', to='finance.cashtransaction', verbose_name='Giao dịch quỹ/ngân hàng')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_receivable_settlements_created', to=settings.AUTH_USER_MODEL)),
                ('receivable_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='finance.receivabledocument', verbose_name='Chứng từ phải thu')),
                ('source_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_settlements_from_bank', to='finance.bankaccount', verbose_name='Ngân hàng thu')),
                ('source_cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_settlements_from_cash', to='finance.cashaccount', verbose_name='Quỹ thu')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_receivable_settlements_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_receivable_settlements',
                'ordering': ['-settlement_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='payabledocument',
            index=models.Index(fields=['code'], name='finance_pay_code_6fbd4a_idx'),
        ),
        migrations.AddIndex(
            model_name='payabledocument',
            index=models.Index(fields=['document_date'], name='finance_pay_documen_588371_idx'),
        ),
        migrations.AddIndex(
            model_name='payabledocument',
            index=models.Index(fields=['due_date'], name='finance_pay_due_dat_163438_idx'),
        ),
        migrations.AddIndex(
            model_name='payabledocument',
            index=models.Index(fields=['status'], name='finance_pay_status_cc76b5_idx'),
        ),
        migrations.AddIndex(
            model_name='payabledocument',
            index=models.Index(fields=['supplier'], name='finance_pay_supplie_b1cb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='payablesettlement',
            index=models.Index(fields=['settlement_date'], name='finance_pay_settlem_f582fc_idx'),
        ),
        migrations.AddIndex(
            model_name='payablesettlement',
            index=models.Index(fields=['payable_document'], name='finance_pay_payable_cb4e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='receivabledocument',
            index=models.Index(fields=['code'], name='finance_rec_code_f4fd59_idx'),
        ),
        migrations.AddIndex(
            model_name='receivabledocument',
            index=models.Index(fields=['document_date'], name='finance_rec_documen_1ad01e_idx'),
        ),
        migrations.AddIndex(
            model_name='receivabledocument',
            index=models.Index(fields=['due_date'], name='finance_rec_due_dat_d69ca4_idx'),
        ),
        migrations.AddIndex(
            model_name='receivabledocument',
            index=models.Index(fields=['status'], name='finance_rec_status_5fd2df_idx'),
        ),
        migrations.AddIndex(
            model_name='receivabledocument',
            index=models.Index(fields=['customer'], name='finance_rec_custome_f0c286_idx'),
        ),
        migrations.AddIndex(
            model_name='receivablesettlement',
            index=models.Index(fields=['settlement_date'], name='finance_rec_settlem_0478cf_idx'),
        ),
        migrations.AddIndex(
            model_name='receivablesettlement',
            index=models.Index(fields=['receivable_document'], name='finance_rec_receiva_b50398_idx'),
        ),
    ]
