# Generated by Django 6.0.2 on 2026-03-15 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payabledocument_payablesettlement_receivabledocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('ASSET', 'Tài sản'), ('LIABILITY', 'Nợ'), ('EQUITY', 'Vốn chủ sở hữu'), ('REVENUE', 'Doanh thu'), ('EXPENSE', 'Chi phí')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Ledger Account',
                'verbose_name_plural': 'General Ledger Accounts',
                'db_table': 'finance_gl_accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(db_index=True)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('document_type', models.CharField(db_index=True, max_length=50)),
                ('document_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('document_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.generalledgeraccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gl_entries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_gl_entries',
                'ordering': ['-posting_date', '-id'],
                'indexes': [models.Index(fields=['account', '-posting_date'], name='finance_gl__account_dace85_idx'), models.Index(fields=['posting_date'], name='finance_gl__posting_c874bc_idx'), models.Index(fields=['document_type', 'document_id'], name='finance_gl__documen_46d868_idx')],
            },
        ),
    ]
