# Generated by Django 6.0.2 on 2026-03-16 12:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_bank_reconciliation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('category', models.CharField(db_index=True, max_length=200)),
                ('fiscal_year', models.PositiveIntegerField(db_index=True)),
                ('budgeted_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_budget_plans_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_budget_plans_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_budget_plans',
                'ordering': ['-fiscal_year', 'department', 'category', '-id'],
                'indexes': [models.Index(fields=['fiscal_year'], name='finance_bud_fiscal__0275c2_idx'), models.Index(fields=['department'], name='finance_bud_departm_3ea36c_idx'), models.Index(fields=['is_active'], name='finance_bud_is_acti_8c28e0_idx')],
            },
        ),
    ]
