# Generated by Django 6.0.2 on 2026-06-24 10:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_receivabledocument_document_type_and_more'),
        ('purchasing', '0006_restore_0005_database_columns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(blank=True, default='')),
                ('direction', models.CharField(choices=[('CREDIT', 'Giảm công nợ'), ('DEBIT', 'Hoàn nhập giảm công nợ')], max_length=10, verbose_name='Chiều điều chỉnh')),
                ('status', models.CharField(choices=[('POSTED', 'Đã ghi sổ')], default='POSTED', max_length=20, verbose_name='Trạng thái')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Số tiền')),
                ('currency', models.CharField(default='VND', max_length=3, verbose_name='Tiền tệ')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18, verbose_name='Tỷ giá')),
                ('idempotency_key', models.CharField(max_length=120, unique=True, verbose_name='Khóa chống ghi trùng')),
                ('reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Lý do')),
                ('note', models.TextField(blank=True, default='', verbose_name='Ghi chú')),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payable_adjustments_created', to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='finance.payabledocument', verbose_name='Chứng từ phải trả')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_payable_adjustments_posted', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_adjustment', to='finance.payableadjustment', verbose_name='Bút toán hoàn nhập')),
                ('source_purchase_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_adjustments', to='purchasing.purchasereceipt', verbose_name='Phiếu nhập nguồn')),
                ('source_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_adjustments', to='purchasing.purchasereturn', verbose_name='Phiếu trả hàng nguồn')),
            ],
            options={
                'db_table': 'finance_payable_adjustments',
                'ordering': ['-posted_at', '-id'],
                'indexes': [models.Index(fields=['payable', 'status'], name='finance_pay_payable_e7d76d_idx'), models.Index(fields=['source_purchase_receipt'], name='finance_pay_source__5ab9fd_idx'), models.Index(fields=['source_return'], name='finance_pay_source__55045b_idx'), models.Index(fields=['direction'], name='finance_pay_directi_783b23_idx'), models.Index(fields=['posted_at'], name='finance_pay_posted__2160dc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payable_adjustment_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('direction', 'CREDIT'), ('reversal_of__isnull', True), ('source_return__isnull', False)), models.Q(('direction', 'DEBIT'), ('reversal_of__isnull', False), ('source_return__isnull', True)), _connector='OR'), name='payable_adjustment_return_direction_ck'), models.UniqueConstraint(condition=models.Q(('direction', 'CREDIT'), ('source_return__isnull', False)), fields=('source_return',), name='one_credit_adjustment_per_purchase_return')],
            },
        ),
    ]
