# Generated by Django 6.0.2 on 2026-06-29 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_payableadjustment'),
        ('purchasing', '0007_purchasereturn_reversal_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payableadjustment',
            name='payable_adjustment_return_direction_ck',
        ),
        migrations.AddConstraint(
            model_name='payableadjustment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'CREDIT'), ('reversal_of__isnull', True), ('source_return__isnull', False)), models.Q(('direction', 'CREDIT'), ('reversal_of__isnull', True), ('source_purchase_receipt__isnull', False), ('source_return__isnull', True)), models.Q(('direction', 'DEBIT'), ('reversal_of__isnull', False), ('source_return__isnull', True)), _connector='OR'), name='payable_adjustment_return_direction_ck'),
        ),
        migrations.AddConstraint(
            model_name='payableadjustment',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'CREDIT'), ('source_purchase_receipt__isnull', False), ('source_return__isnull', True)), fields=('source_purchase_receipt',), name='one_credit_adjustment_per_receipt_cancel'),
        ),
    ]
