from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_pricechange'),
        ('sales', '0003_salesorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã kho', max_length=20)),
                ('name', models.CharField(help_text='Tên kho', max_length=200)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouses', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_warehouses', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_warehouses',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã vị trí', max_length=30)),
                ('name', models.CharField(help_text='Tên vị trí', max_length=200)),
                ('location_type', models.CharField(choices=[('STORAGE', 'Lưu trữ'), ('STAGING', 'Chờ xử lý'), ('SHIPPING', 'Xuất hàng'), ('RETURN', 'Hàng trả'), ('PRODUCTION', 'Sản xuất'), ('OTHER', 'Khác')], default='STORAGE', max_length=20)),
                ('allow_mixed_products', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouse_locations', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_warehouse_locations', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.warehouselocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_warehouse_locations', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_warehouse_locations',
                'ordering': ['warehouse__sort_order', 'warehouse__code', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Đang giữ'), ('RELEASED', 'Đã nhả'), ('FULFILLED', 'Đã xuất đủ'), ('CANCELLED', 'Đã hủy')], db_index=True, default='OPEN', max_length=20)),
                ('reservation_date', models.DateField(db_index=True)),
                ('reserved_qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('released_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('fulfilled_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_inventory_reservations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_reservations', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouselocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='products.product')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservations', to='sales.salesorder')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservations', to='sales.salesorderline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_reservations', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_reservations',
                'ordering': ['-reservation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', 'Nhập kho'), ('ISSUE', 'Xuất kho'), ('TRANSFER', 'Chuyển kho'), ('ADJUSTMENT_IN', 'Điều chỉnh tăng'), ('ADJUSTMENT_OUT', 'Điều chỉnh giảm')], max_length=20)),
                ('status', models.CharField(choices=[('POSTED', 'Đã ghi sổ'), ('CANCELLED', 'Đã hủy')], db_index=True, default='POSTED', max_length=20)),
                ('transaction_date', models.DateField(db_index=True)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.warehouselocation')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.product')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.inventoryreservation')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='sales.salesorder')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='sales.salesorderline')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='inventory.warehouselocation')),
                ('target_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='inventory.warehouse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_transactions',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.AddIndex(model_name='warehouse', index=models.Index(fields=['code'], name='inventory_wa_code_6485d7_idx')),
        migrations.AddIndex(model_name='warehouse', index=models.Index(fields=['name'], name='inventory_wa_name_5d9af8_idx')),
        migrations.AddIndex(model_name='warehouse', index=models.Index(fields=['is_active'], name='inventory_wa_is_acti_529ef2_idx')),
        migrations.AddConstraint(model_name='warehouse', constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='warehouse_code_uniq_active')),
        migrations.AddIndex(model_name='warehouselocation', index=models.Index(fields=['warehouse', 'code'], name='inventory_wa_warehou_4a8e2a_idx')),
        migrations.AddIndex(model_name='warehouselocation', index=models.Index(fields=['warehouse', 'is_active'], name='inventory_wa_warehou_532c14_idx')),
        migrations.AddIndex(model_name='warehouselocation', index=models.Index(fields=['location_type'], name='inventory_wa_locatio_6f93d2_idx')),
        migrations.AddConstraint(model_name='warehouselocation', constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('warehouse', 'code'), name='warehouse_location_code_uniq_active')),
        migrations.AddIndex(model_name='inventoryreservation', index=models.Index(fields=['status'], name='inventory_in_status_8d84cb_idx')),
        migrations.AddIndex(model_name='inventoryreservation', index=models.Index(fields=['reservation_date'], name='inventory_in_reserva_17f1cb_idx')),
        migrations.AddIndex(model_name='inventoryreservation', index=models.Index(fields=['product', 'warehouse'], name='inventory_in_product_69aa1a_idx')),
        migrations.AddIndex(model_name='inventoryreservation', index=models.Index(fields=['sales_order'], name='inventory_in_sales_o_7516a5_idx')),
        migrations.AddIndex(model_name='inventorytransaction', index=models.Index(fields=['transaction_date'], name='inventory_in_transac_8728e4_idx')),
        migrations.AddIndex(model_name='inventorytransaction', index=models.Index(fields=['transaction_type'], name='inventory_in_transac_3c0707_idx')),
        migrations.AddIndex(model_name='inventorytransaction', index=models.Index(fields=['status'], name='inventory_in_status_f71478_idx')),
        migrations.AddIndex(model_name='inventorytransaction', index=models.Index(fields=['product', 'warehouse'], name='inventory_in_product_4c15c4_idx')),
        migrations.AddIndex(model_name='inventorytransaction', index=models.Index(fields=['sales_order'], name='inventory_in_sales_o_8284ba_idx')),
    ]
