# Generated by Django 6.0.2 on 2026-03-13 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_inventory_in_status_8d84cb_idx_inventory_r_status_c8c2fd_idx_and_more'),
        ('products', '0012_bundlepricechange'),
        ('purchasing', '0001_initial'),
        ('sales', '0005_salesorderdeliveryplan_shipped_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='purchase_order_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='purchasing.purchaseorderline'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='purchase_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='purchasing.purchasereceipt'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['purchase_order'], name='inventory_t_purchas_d331a0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['purchase_receipt'], name='inventory_t_purchas_78d85c_idx'),
        ),
    ]
