# Generated by Django 6.0.2 on 2026-03-13 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorytransaction_purchase_order_and_more'),
        ('production', '0001_initial'),
        ('products', '0012_bundlepricechange'),
        ('purchasing', '0001_initial'),
        ('sales', '0005_salesorderdeliveryplan_shipped_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='production_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='production.productionissue'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='production_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='production.productionreceipt'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['production_order'], name='inventory_t_product_642b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['production_issue'], name='inventory_t_product_4d2cad_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['production_receipt'], name='inventory_t_product_5a5962_idx'),
        ),
    ]
