# Generated by Django 6.0.2 on 2026-03-15 03:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorytransaction_production_issue_and_more'),
        ('products', '0012_bundlepricechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocktake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('count_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('COMPLETED', 'Đã hoàn tất'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_stocktakes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stocktakes', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktakes', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Phiếu kiểm tồn',
                'verbose_name_plural': 'Phiếu kiểm tồn',
                'db_table': 'inventory_stocktakes',
                'ordering': ['-count_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StocktakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('system_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tồn theo hệ thống tại thời điểm kiểm', max_digits=18)),
                ('count_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Số lượng đếm thực tế', max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='products.product')),
                ('stocktake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktake')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocktake_lines', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Dòng kiểm tồn',
                'verbose_name_plural': 'Dòng kiểm tồn',
                'db_table': 'inventory_stocktake_lines',
                'ordering': ['stocktake', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['count_date'], name='inventory_s_count_d_5d9196_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['status'], name='inventory_s_status_379926_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktake',
            index=models.Index(fields=['warehouse'], name='inventory_s_warehou_98b8fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocktakeline',
            unique_together={('stocktake', 'line_number')},
        ),
    ]
