# Generated by Django 6.0.2 on 2026-03-15 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_add_stocktake'),
        ('products', '0012_bundlepricechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Tồn kho thấp'), ('OUT_OF_STOCK', 'Hết hàng')], default='LOW_STOCK', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang hoạt động'), ('ACKNOWLEDGED', 'Đã xác nhận'), ('RESOLVED', 'Đã giải quyết')], db_index=True, default='ACTIVE', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('current_qty', models.DecimalField(decimal_places=4, max_digits=18)),
                ('min_stock', models.DecimalField(decimal_places=4, max_digits=18)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_stock_alerts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='products.product')),
            ],
            options={
                'verbose_name': 'Cảnh báo tồn kho',
                'verbose_name_plural': 'Cảnh báo tồn kho',
                'db_table': 'inventory_stock_alerts',
                'ordering': ['-triggered_at'],
                'indexes': [models.Index(fields=['status'], name='inventory_s_status_daeb73_idx'), models.Index(fields=['product'], name='inventory_s_product_08f86a_idx')],
            },
        ),
    ]
