# Generated by Django 6.0.2 on 2026-03-15 13:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_stock_alert'),
        ('products', '0012_bundlepricechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transfer_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Chờ xác nhận'), ('IN_TRANSIT', 'Đang vận chuyển'), ('RECEIVED', 'Đã nhận'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers_cancelled', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='inventory.warehouse')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers_posted', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_transfers_submitted', to=settings.AUTH_USER_MODEL)),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Chuyển kho',
                'verbose_name_plural': 'Chuyển kho',
                'db_table': 'inventory_warehouse_transfers',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveSmallIntegerField(default=1)),
                ('qty', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('received_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_transfer_lines', to='products.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.warehousetransfer')),
            ],
            options={
                'db_table': 'inventory_warehouse_transfer_lines',
                'ordering': ['transfer_id', 'line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['code'], name='inventory_w_code_3564b6_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['transfer_date'], name='inventory_w_transfe_e38880_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousetransfer',
            index=models.Index(fields=['status'], name='inventory_w_status_f43252_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehousetransferline',
            unique_together={('transfer', 'line_number')},
        ),
    ]
