# Generated by Django 6.0.2 on 2026-04-02 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_add_warehouse_transfer'),
        ('sales', '0013_deliverycarrier_outboundshipment_carrier_master_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundshipment',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_shipments', to='sales.deliverycarrier'),
        ),
    ]
