# Generated by Django 6.0.2 on 2026-05-11 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_outboundshipment_carrier'),
        ('production', '0009_productionworkcenter_productionmachine'),
        ('products', '0018_product_routing_step'),
        ('purchasing', '0005_purchaseorderlinematerialallocation_and_more'),
        ('sales', '0013_deliverycarrier_outboundshipment_carrier_master_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='stocktake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_transactions', to='inventory.stocktake'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='stocktake_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_transactions', to='inventory.stocktakeline'),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='adjustment_posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktake',
            name='adjustment_posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_posted_stocktakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['stocktake'], name='inventory_t_stockta_d03df5_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['stocktake_line'], name='inventory_t_stockta_64644c_idx'),
        ),
    ]
