# Generated by Django 6.0.2 on 2026-03-03 09:49

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_sales_order_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderDeliveryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(db_index=True)),
                ('qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('delivered_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_plans', to='sales.salesorderline')),
            ],
            options={
                'verbose_name': 'Sales Order Delivery Plan',
                'verbose_name_plural': 'Sales Order Delivery Plans',
                'db_table': 'sales_order_delivery_plans',
                'ordering': ['delivery_date', 'id'],
                'indexes': [models.Index(fields=['delivery_date'], name='sales_order_deliver_b3c483_idx'), models.Index(fields=['line', 'delivery_date'], name='sales_order_line_id_277b77_idx')],
            },
        ),
    ]
