# Generated by Django 6.0.2 on 2026-03-03 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_rename_task_watche_user_id_8d1637_idx_task_watche_user_id_f5295c_idx_and_more'),
        ('sales', '0002_salesorderdeliveryplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['delivery_date'], name='sales_order_deliver_35fd00_idx'),
        ),
    ]
