# Generated by Django 6.0.2 on 2026-03-15 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_quote_quoteline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quote',
            new_name='sales_quote_code_f149b3_idx',
            old_name='sales_quote_code_idx',
        ),
        migrations.RenameIndex(
            model_name='quote',
            new_name='sales_quote_quote_d_2b478d_idx',
            old_name='sales_quote_quote_d_idx',
        ),
        migrations.RenameIndex(
            model_name='quote',
            new_name='sales_quote_valid_u_120cd1_idx',
            old_name='sales_quote_valid_u_idx',
        ),
        migrations.RenameIndex(
            model_name='quote',
            new_name='sales_quote_status_54d30a_idx',
            old_name='sales_quote_status_idx',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders_confirmed', to=settings.AUTH_USER_MODEL),
        ),
    ]
