# Generated by Django 6.0.2 on 2026-03-15 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_seed_stocktake_permission'),
        ('products', '0012_bundlepricechange'),
        ('sales', '0007_add_order_confirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('shipment_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Chờ duyệt'), ('APPROVED', 'Đã duyệt'), ('PACKED', 'Đã đóng gói'), ('IN_TRANSIT', 'Đang vận chuyển'), ('DELIVERED', 'Đã giao'), ('RETURNED', 'Đã trả'), ('CANCELLED', 'Đã hủy')], db_index=True, default='DRAFT', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('carrier', models.CharField(blank=True, max_length=100)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('shipping_address', models.TextField(blank=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_by', models.CharField(blank=True, max_length=100)),
                ('delivery_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('total_qty', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('total_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='core.customer')),
                ('delivered_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_delivered', to=settings.AUTH_USER_MODEL)),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_packed', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='sales.salesorder')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_outbound_shipments',
                'ordering': ['-shipment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('qty_ordered', models.DecimalField(decimal_places=4, max_digits=18)),
                ('qty_shipped', models.DecimalField(decimal_places=4, max_digits=18)),
                ('qty_received', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight_per_unit', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.outboundshipment')),
            ],
            options={
                'db_table': 'sales_shipment_lines',
                'ordering': ['line_number'],
            },
        ),
        migrations.AddIndex(
            model_name='outboundshipment',
            index=models.Index(fields=['status', '-shipment_date'], name='sales_outbo_status_822a37_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundshipment',
            index=models.Index(fields=['customer', 'status'], name='sales_outbo_custome_3937fa_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundshipment',
            index=models.Index(fields=['sales_order', 'status'], name='sales_outbo_sales_o_55406d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentline',
            unique_together={('shipment', 'line_number')},
        ),
    ]
