# Generated by Django 6.0.2 on 2026-03-16 12:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_add_shipment_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesDiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('PERCENTAGE', 'Phan tram'), ('FIXED', 'Co dinh')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('applicable_to', models.CharField(choices=[('ALL_PRODUCTS', 'Tat ca san pham'), ('SPECIFIC_PRODUCTS', 'San pham chon'), ('SPECIFIC_CUSTOMERS', 'Khach hang chon'), ('VOLUME_BASED', 'Theo so luong')], default='ALL_PRODUCTS', max_length=30)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('min_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Hoat dong'), ('INACTIVE', 'Khong hoat dong')], db_index=True, default='ACTIVE', max_length=20)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('total_discount_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_discount_rules_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_discount_rules_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_discount_rules',
                'ordering': ['-created_at', 'code'],
                'indexes': [models.Index(fields=['code'], name='sales_disco_code_053d74_idx'), models.Index(fields=['status'], name='sales_disco_status_57d135_idx'), models.Index(fields=['type'], name='sales_disco_type_44e637_idx'), models.Index(fields=['applicable_to'], name='sales_disco_applica_bcf438_idx'), models.Index(fields=['start_date', 'end_date'], name='sales_disco_start_d_8fa134_idx')],
            },
        ),
    ]
