# Generated by Django 6.0.2 on 2026-03-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesdiscountrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdiscountrule',
            name='applicable_to',
            field=models.CharField(choices=[('ALL_PRODUCTS', 'Tất cả sản phẩm'), ('SPECIFIC_PRODUCTS', 'Sản phẩm chọn'), ('SPECIFIC_CUSTOMERS', 'Khách hàng chọn'), ('VOLUME_BASED', 'Theo số lượng')], default='ALL_PRODUCTS', max_length=30),
        ),
        migrations.AlterField(
            model_name='salesdiscountrule',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('INACTIVE', 'Không hoạt động')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesdiscountrule',
            name='type',
            field=models.CharField(choices=[('PERCENTAGE', 'Phần trăm'), ('FIXED', 'Cố định')], default='PERCENTAGE', max_length=20),
        ),
    ]
