# Generated by Django 6.0.2 on 2026-03-31 03:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_material_template_models'),
        ('sales', '0010_alter_salesdiscountrule_applicable_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesLineMaterialPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_finished_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('CONFIRMED', 'Đã chốt vật tư'), ('PARTIAL_ORDERED', 'Đã đặt mua một phần'), ('PARTIAL_RECEIVED', 'Đã về một phần'), ('READY', 'Sẵn sàng')], db_index=True, default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_line_material_plans_confirmed', to=settings.AUTH_USER_MODEL)),
                ('finished_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_material_plans', to='products.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_plans', to='sales.salesorder')),
                ('sales_order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material_plan', to='sales.salesorderline')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_line_plans', to='products.productmaterialtemplate')),
            ],
            options={
                'db_table': 'sales_line_material_plans',
                'ordering': ['sales_order_id', 'sales_order_line_id'],
            },
        ),
        migrations.CreateModel(
            name='SalesLineMaterialPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_code_snapshot', models.CharField(blank=True, db_index=True, max_length=50)),
                ('group_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('material_role', models.CharField(db_index=True, default='PRIMARY', max_length=20)),
                ('selection_rule', models.CharField(db_index=True, default='ONE_OF', max_length=20)),
                ('spec_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_selected', models.BooleanField(db_index=True, default=False)),
                ('required_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('ordered_qty_cache', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('received_qty_cache', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('available_qty_cache', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('short_qty_cache', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_material_plan_items', to='products.product')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleslinematerialplan')),
                ('template_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_plan_items', to='products.productmaterialgroup')),
                ('template_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_plan_items', to='products.productmaterialoption')),
            ],
            options={
                'db_table': 'sales_line_material_plan_items',
                'ordering': ['plan_id', 'group_code_snapshot', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='saleslinematerialplan',
            index=models.Index(fields=['sales_order'], name='sales_line__sales_o_cae5a9_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslinematerialplan',
            index=models.Index(fields=['sales_order_line'], name='sales_line__sales_o_54ac3a_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslinematerialplan',
            index=models.Index(fields=['finished_product'], name='sales_line__finishe_378116_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslinematerialplan',
            index=models.Index(fields=['status'], name='sales_line__status_6361fc_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslinematerialplanitem',
            index=models.Index(fields=['plan'], name='sales_line__plan_id_910f0f_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslinematerialplanitem',
            index=models.Index(fields=['material_product'], name='sales_line__materia_15ccd7_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslinematerialplanitem',
            index=models.Index(fields=['is_selected'], name='sales_line__is_sele_c98cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='saleslinematerialplanitem',
            index=models.Index(fields=['group_code_snapshot'], name='sales_line__group_c_399d2d_idx'),
        ),
    ]
