# Generated by Django 6.0.2 on 2026-04-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_material_plan_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderdeliveryplan',
            name='delivery_rule',
            field=models.CharField(choices=[('FULL_REQUIRED', 'Giao đủ'), ('PARTIAL_ALLOWED', 'Cho phép sớt lại')], db_index=True, default='PARTIAL_ALLOWED', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorderdeliveryplan',
            name='planned_carrier_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='salesorderdeliveryplan',
            index=models.Index(fields=['delivery_rule', 'delivery_date'], name='sales_order_deliver_98e933_idx'),
        ),
    ]
