# Generated by Django 6.0.2 on 2026-04-02 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesorderdeliveryplan_delivery_rule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_carriers', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_delivery_carriers', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_delivery_carriers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Carrier',
                'verbose_name_plural': 'Delivery Carriers',
                'db_table': 'sales_delivery_carriers',
                'ordering': ['sort_order', 'name', 'code'],
            },
        ),
        migrations.AddField(
            model_name='outboundshipment',
            name='carrier_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_shipments', to='sales.deliverycarrier'),
        ),
        migrations.AddField(
            model_name='salesorderdeliveryplan',
            name='planned_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_plans', to='sales.deliverycarrier'),
        ),
        migrations.AddIndex(
            model_name='deliverycarrier',
            index=models.Index(fields=['code'], name='sales_deliv_code_7a4677_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverycarrier',
            index=models.Index(fields=['name'], name='sales_deliv_name_3c3f04_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverycarrier',
            index=models.Index(fields=['is_active'], name='sales_deliv_is_acti_29b047_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverycarrier',
            index=models.Index(fields=['is_internal'], name='sales_deliv_is_inte_ed3fbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverycarrier',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='delivery_carrier_code_uniq_active'),
        ),
    ]
