# Generated by Django 6.0.2 on 2026-07-03 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_task_is_all_day_task_schedule_is_exception_and_more'),
        ('sales', '0013_deliverycarrier_outboundshipment_carrier_master_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='converted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='source_quote',
            field=models.OneToOneField(blank=True, help_text='Quote that created this sales order. Nullable for legacy orders.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_order', to='sales.quote'),
        ),
    ]
