# Generated by Django 6.0.2 on 2026-04-30 16:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_productionoperation_dispatch_sequence_and_more'),
        ('products', '0018_product_routing_step'),
        ('sales', '0013_deliverycarrier_outboundshipment_carrier_master_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField(blank=True, default='')),
                ('demand_code', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('demand_key', models.CharField(db_index=True, max_length=200, unique=True)),
                ('customer_id_snapshot', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('customer_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('product_code', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_kind', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('unit_name', models.CharField(blank=True, default='', max_length=80)),
                ('size_order', models.CharField(blank=True, default='', max_length=255)),
                ('size_production', models.CharField(blank=True, default='', max_length=255)),
                ('print_colors', models.JSONField(blank=True, default=list)),
                ('operations_summary', models.JSONField(blank=True, default=list)),
                ('routing_summary', models.JSONField(blank=True, default=list)),
                ('qty_required', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('qty_planned', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('qty_released', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('qty_completed', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('order_date', models.DateField(blank=True, db_index=True, null=True)),
                ('delivery_date', models.DateField(blank=True, db_index=True, null=True)),
                ('production_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('planning_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reminder_date', models.DateField(blank=True, db_index=True, null=True)),
                ('planning_status', models.CharField(choices=[('NOT_DUE', 'Not due'), ('UPCOMING', 'Upcoming'), ('DUE', 'Due'), ('OVERDUE', 'Overdue'), ('PARTIALLY_PLANNED', 'Partially planned'), ('FULLY_PLANNED', 'Fully planned'), ('NO_PRODUCTION_NEEDED', 'No production needed'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_DUE', max_length=30)),
                ('production_status', models.CharField(choices=[('NOT_RELEASED', 'Not released'), ('PARTIALLY_RELEASED', 'Partially released'), ('FULLY_RELEASED', 'Fully released'), ('IN_PROGRESS', 'In progress'), ('PARTIALLY_COMPLETED', 'Partially completed'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_RELEASED', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('reminder_note', models.TextField(blank=True, default='')),
                ('hold_reason', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, db_index=True, default='SALES_ORDER', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_planner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_production_demands', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_demands_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_demands', to='sales.salesorderdeliveryplan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_demands', to='products.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_demands', to='sales.salesorder')),
                ('sales_order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_demands', to='sales.salesorderline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_demands_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'production_demands',
                'ordering': ['planning_due_date', 'delivery_date', 'id'],
                'indexes': [models.Index(fields=['planning_status'], name='production__plannin_07af1d_idx'), models.Index(fields=['production_status'], name='production__product_a11cf3_idx'), models.Index(fields=['planning_due_date'], name='production__plannin_7a81a2_idx'), models.Index(fields=['delivery_date'], name='production__deliver_190289_idx'), models.Index(fields=['product_code'], name='production__product_b20aba_idx'), models.Index(fields=['product_kind'], name='production__product_d5016a_idx'), models.Index(fields=['assigned_planner'], name='production__assigne_fab40f_idx'), models.Index(fields=['priority'], name='production__priorit_7dec2b_idx'), models.Index(fields=['source'], name='production__source_4f1d29_idx')],
            },
        ),
    ]
