# Generated by Django 6.0.2 on 2026-05-04 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_production_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionoperation',
            name='allow_parallel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='display_step',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='group_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='route_step_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='source_operation_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='productionoperation',
            name='step_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.productiondemand'),
        ),
    ]
