# Generated by Django 6.0.2 on 2026-05-08 18:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_operation_skip_audit_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionWorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('default_capacity_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'production_work_centers',
                'ordering': ['sort_order', 'name', 'code'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='production__is_acti_420a30_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductionMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('default_capacity_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='production.productionworkcenter')),
            ],
            options={
                'db_table': 'production_machines',
                'ordering': ['work_center__sort_order', 'work_center__name', 'sort_order', 'name', 'code'],
                'indexes': [models.Index(fields=['work_center', 'is_active', 'sort_order'], name='production__work_ce_4d0433_idx')],
            },
        ),
    ]
