# Generated by Django 5.0 on 2026-01-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Role code (e.g., ADMIN, MANAGER)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Role description')),
                ('is_active', models.BooleanField(default=True, help_text='Is this role active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
    ]
