# Generated by Django 5.0 on 2026-01-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Permission name', max_length=100)),
                ('code', models.CharField(help_text='Permission code (e.g., USER_CREATE)', max_length=100, unique=True)),
                ('resource', models.CharField(help_text='Resource name (e.g., USER, INVOICE)', max_length=50)),
                ('action', models.CharField(help_text='Action name (e.g., CREATE, VIEW, EDIT, DELETE)', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Permission description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['resource', 'action'],
                'unique_together': {('resource', 'action')},
            },
        ),
    ]
