# Generated by Django 5.0 on 2026-01-24 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
