# Generated by Django 5.0 on 2026-01-24 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles assigned to this user', related_name='users', to='core.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this role was created'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Role name (e.g., Admin, Manager)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this role was last updated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='User avatar', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When the account was locked', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='locked_by',
            field=models.ForeignKey(blank=True, help_text='User who locked this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
