# Generated by Django 5.0 on 2026-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_options_user_roles_alter_role_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Team name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Team code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Team description')),
                ('is_active', models.BooleanField(default=True, help_text='Is this team active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
                'ordering': ['name'],
            },
        ),
    ]
