# Generated by Django 5.0 on 2026-01-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(blank=True, help_text='Teams this user belongs to', related_name='users', to='core.team'),
        ),
    ]
