# Generated by Django 5.0 on 2026-01-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key (e.g., MAX_LOGIN_ATTEMPTS)', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value (stored as text)')),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', help_text='Data type of the value', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Setting description')),
                ('is_active', models.BooleanField(default=True, help_text='Is this setting active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'db_table': 'settings',
                'ordering': ['key'],
            },
        ),
    ]
