# Generated by Django 5.0 on 2026-01-26 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Customer code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Customer name', max_length=200)),
                ('company_name', models.CharField(blank=True, help_text='Company name', max_length=200)),
                ('tax_code', models.CharField(blank=True, help_text='Tax identification number', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Address')),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=100)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact person phone', max_length=20)),
                ('payment_terms', models.IntegerField(default=30, help_text='Payment terms in days')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Credit limit', max_digits=15)),
                ('is_active', models.BooleanField(default=True, help_text='Is customer active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Created by user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Updated by user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['code'],
            },
        ),
    ]
