# Generated by Django 6.0.1 on 2026-01-27 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name (e.g., Customer - Full)', max_length=100)),
                ('entity_type', models.CharField(help_text='Entity type (e.g., Customer, SalesOrder)', max_length=50)),
                ('columns', models.JSONField(help_text="List of field names ['code', 'name', 'phone']")),
                ('headers', models.JSONField(help_text="List of header names ['Mã KH', 'Tên KH', 'SĐT']")),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default template for this entity?')),
                ('is_active', models.BooleanField(default=True, help_text='Is template active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Created by user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Template',
                'verbose_name_plural': 'Export Templates',
                'db_table': 'export_templates',
                'ordering': ['entity_type', 'name'],
                'unique_together': {('entity_type', 'name')},
            },
        ),
    ]
