# Generated by Django 5.0 on 2026-01-27 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_exporttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='View name', max_length=100)),
                ('entity_type', models.CharField(help_text='Entity type (e.g., Customer, SalesOrder)', max_length=50)),
                ('filters', models.JSONField(default=dict, help_text="Filter parameters {'status': 'APPROVED', 'total__gte': 1000000}")),
                ('sorting', models.CharField(blank=True, help_text='Sorting parameter (e.g., -created_at)', max_length=100)),
                ('columns', models.JSONField(default=list, help_text="Visible columns ['code', 'customer__name', 'total']")),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default view for this user/entity?')),
                ('is_public', models.BooleanField(default=False, help_text='Is this view public (shared with all users)?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_saved_views', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Owner of this view. Null = shared/public view', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved View',
                'verbose_name_plural': 'Saved Views',
                'db_table': 'saved_views',
                'ordering': ['entity_type', 'name'],
                'unique_together': {('user', 'entity_type', 'name')},
            },
        ),
    ]
