# Generated by Django 5.0 on 2026-01-28 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_savedview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='Entity type (Customer, Product...)', max_length=50)),
                ('filename', models.CharField(help_text='Uploaded filename', max_length=255)),
                ('total_rows', models.IntegerField(default=0, help_text='Total rows in file')),
                ('success_count', models.IntegerField(default=0, help_text='Successfully imported')),
                ('error_count', models.IntegerField(default=0, help_text='Failed rows')),
                ('errors', models.JSONField(default=list, help_text='List of errors [{row, error}]')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'db_table': 'import_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
