# Generated by Django 5.0 on 2026-01-28 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_importlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('POST', 'Post'), ('LOCK', 'Lock')], max_length=20)),
                ('entity_type', models.CharField(help_text='Model name (Customer, SalesOrder...)', max_length=50)),
                ('entity_id', models.IntegerField(help_text='Record ID')),
                ('entity_code', models.CharField(blank=True, help_text='Record code (for display)', max_length=50)),
                ('old_values', models.JSONField(blank=True, help_text='Values before change', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Values after change', null=True)),
                ('changed_fields', models.JSONField(default=list, help_text='List of changed field names')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_logs_entity__d4c2e5_idx'), models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx')],
            },
        ),
    ]
