# Generated by Django 5.0 on 2026-01-28 04:01

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='Model name (Customer, SalesOrder...)', max_length=50)),
                ('entity_id', models.IntegerField(help_text='Record ID')),
                ('file', models.FileField(upload_to=core.models.attachment_upload_path)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, help_text='MIME type', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachments',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='attachments_entity__d756e0_idx')],
            },
        ),
    ]
