# Generated by Django 5.0 on 2026-01-28 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='Model name (Customer, SalesOrder...)', max_length=50)),
                ('entity_id', models.IntegerField(help_text='Record ID')),
                ('content', models.TextField(help_text='Comment text')),
                ('mentions', models.JSONField(default=list, help_text='List of mentioned @usernames')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='comments_entity__ecb426_idx'), models.Index(fields=['created_by', 'created_at'], name='comments_created_971cde_idx')],
            },
        ),
    ]
