# Generated by Django 5.0 on 2026-01-28 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_customer_approved_at_customer_approved_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField()),
                ('entity_code', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(choices=[('SUBMIT', 'Submitted for approval'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('REVOKE', 'Revoked approval'), ('RESUBMIT', 'Resubmitted')], max_length=20)),
                ('comments', models.TextField(blank=True, help_text="Approver's comments")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.IntegerField(default=1, help_text='Approval level')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval History',
                'verbose_name_plural': 'Approval History',
                'db_table': 'approval_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='approval_hi_entity__254ce6_idx'), models.Index(fields=['user', 'created_at'], name='approval_hi_user_id_ba75ab_idx')],
            },
        ),
    ]
