# Generated by Django 5.0 on 2026-01-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_approvalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='Entity type (Customer, SalesOrder, Invoice...)', max_length=50, unique=True)),
                ('prefix', models.CharField(help_text='Prefix (CUST, SO, INV...)', max_length=10)),
                ('current_number', models.IntegerField(default=0, help_text='Current number')),
                ('padding', models.IntegerField(default=3, help_text='Number of digits (3 = 001, 4 = 0001)')),
                ('format_template', models.CharField(default='{prefix}-{number}', help_text='Format: {prefix}-{number} or {prefix}-{YYYY}-{number}', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Number Sequence',
                'verbose_name_plural': 'Number Sequences',
                'db_table': 'number_sequences',
            },
        ),
    ]
