# Generated by Django 5.0 on 2026-01-28 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tag_entitytag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team that owns this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_customers', to='core.team'),
        ),
    ]
