# Generated by Django 5.0 on 2026-01-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_customer_owner_customer_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='Entity type (Customer, SalesOrder, Invoice...)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Workflow name', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('states', models.JSONField(help_text="List of states [{'code': 'DRAFT', 'name': 'Draft', 'color': '#gray'}]")),
                ('transitions', models.JSONField(help_text="List of transitions [{'from': 'DRAFT', 'to': 'PENDING', 'action': 'submit', 'required_permission': 'sales.order.create'}]")),
                ('initial_state', models.CharField(default='DRAFT', help_text='Initial state when creating new record', max_length=50)),
                ('final_states', models.JSONField(default=list, help_text="List of final states ['APPROVED', 'POSTED']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workflow Definition',
                'verbose_name_plural': 'Workflow Definitions',
                'db_table': 'workflow_definitions',
            },
        ),
    ]
