# Generated by Django 5.0 on 2026-01-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('min_length', models.IntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_lowercase', models.BooleanField(default=True)),
                ('require_digit', models.BooleanField(default=True)),
                ('require_special', models.BooleanField(default=False)),
                ('prevent_reuse_count', models.IntegerField(default=3, help_text='Prevent reusing last N passwords')),
                ('expire_days', models.IntegerField(default=0, help_text='Password expires after N days (0 = never)')),
                ('force_change_first_login', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Password Policy',
                'verbose_name_plural': 'Password Policies',
                'db_table': 'password_policies',
            },
        ),
    ]
