# Generated by Django 5.0 on 2026-01-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_passwordpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text='Entity type (Customer, SalesOrder, Invoice...)', max_length=50)),
                ('level', models.IntegerField(help_text='Approval level order (1, 2, 3, ...)')),
                ('name', models.CharField(help_text='Level name (e.g. Manager approval)', max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum amount requiring this level (0 = always)', max_digits=15)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('required_role', models.ForeignKey(blank=True, help_text='Role required to approve at this level', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role')),
            ],
            options={
                'verbose_name': 'Approval Level',
                'verbose_name_plural': 'Approval Levels',
                'db_table': 'approval_levels',
                'ordering': ['entity_type', 'level'],
                'unique_together': {('entity_type', 'level')},
            },
        ),
    ]
