# Generated by Django 5.0 on 2026-01-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_approvallevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(help_text='Notification type (mention, approval_request...)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(help_text='Email subject (supports variables)', max_length=200)),
                ('body_html', models.TextField(help_text='HTML email body (supports variables)')),
                ('body_text', models.TextField(blank=True, help_text='Plain text email body')),
                ('available_variables', models.JSONField(default=list, help_text="List of available variables: ['user_name', 'title', 'message', 'link']")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'email_templates',
            },
        ),
    ]
