# Generated by Django 5.0 on 2026-02-05 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_column_permission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='columnpermission',
            new_name='column_perm_page_27f4c8_idx',
            old_name='column_perm_page_id_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='userpreferences',
            new_name='user_prefer_user_id_30a8b9_idx',
            old_name='user_pref_user_page_idx',
        ),
    ]
