# Generated by Django 6.0.2 on 2026-02-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_column_perm_page_id_8a1b2c_idx_column_perm_page_27f4c8_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['code'], name='customers_code_083fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='customers_name_25d5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['is_active'], name='customers_is_acti_0e47e3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['team'], name='customers_team_id_4b8da2_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='customers_created_c63477_idx'),
        ),
    ]
