# Generated by Django 6.0.2 on 2026-02-11 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_customer_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
        migrations.AddField(
            model_name='role',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='role',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa (soft)'),
        ),
        migrations.AddField(
            model_name='role',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_roles', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa'),
        ),
        migrations.AddField(
            model_name='role',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_roles', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teams', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='team',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày xóa (soft)'),
        ),
        migrations.AddField(
            model_name='team',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_teams', to=settings.AUTH_USER_MODEL, verbose_name='Người xóa'),
        ),
        migrations.AddField(
            model_name='team',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_teams', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('POST', 'Post'), ('LOCK', 'Lock'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text='Role code (unique trong bản ghi chưa xóa)', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Role name (e.g., Admin, Manager)', max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(help_text='Team code (unique trong bản ghi chưa xóa)', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Team name', max_length=100),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='roles_code_25c050_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='roles_name_a96913_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='roles_is_acti_723ee4_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['created_at'], name='roles_created_e4bab6_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['code'], name='teams_code_33f796_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['name'], name='teams_name_12b53a_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['is_active'], name='teams_is_acti_dd3222_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_at'], name='teams_created_d88c0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='role_code_uniq_active'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='team_code_uniq_active'),
        ),
    ]
