# Generated by Django 6.0.2 on 2026-02-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_team_role_master_data_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('POST', 'Post'), ('LOCK', 'Lock'), ('ACTIVATE', 'Activate'), ('DEACTIVATE', 'Deactivate'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('VOID', 'Void'), ('SUBMIT', 'Submit')], max_length=20),
        ),
    ]
