# Generated by Django 6.0.2 on 2026-02-26 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auditlog_entity_id_str'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Loại đối tượng')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID đối tượng')),
                ('entity_code', models.CharField(blank=True, max_length=100, verbose_name='Mã đối tượng')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('status', models.CharField(choices=[('TODO', 'Chờ thực hiện'), ('IN_PROGRESS', 'Đang thực hiện'), ('DONE', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='TODO', max_length=20, verbose_name='Trạng thái')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('URGENT', 'Khẩn cấp')], default='MEDIUM', max_length=20, verbose_name='Ưu tiên')),
                ('is_blocking', models.BooleanField(default=False, verbose_name='Chặn sản xuất')),
                ('blocks_action', models.CharField(blank=True, help_text='VD: RELEASE, APPROVE. Để trống = chặn tất cả.', max_length=50, verbose_name='Hành động bị chặn')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn hoàn thành')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người giao')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhiệm vụ',
                'verbose_name_plural': 'Nhiệm vụ',
                'db_table': 'tasks',
                'ordering': ['-is_blocking', 'due_date', '-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='tasks_entity__82599f_idx'), models.Index(fields=['assigned_to'], name='tasks_assigne_00feb5_idx'), models.Index(fields=['status'], name='tasks_status_031d4c_idx'), models.Index(fields=['is_blocking', 'status'], name='tasks_is_bloc_4b6464_idx')],
            },
        ),
    ]
