# Generated by Django 6.0.2 on 2026-02-26 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_task_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='help_reason',
            field=models.TextField(blank=True, verbose_name='Lý do cần hỗ trợ'),
        ),
        migrations.AddField(
            model_name='task',
            name='help_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm báo cần hỗ trợ'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_update_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cập nhật tiến độ lần cuối'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_update_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú tiến độ'),
        ),
        migrations.AddField(
            model_name='task',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_notes', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật tiến độ'),
        ),
        migrations.AddField(
            model_name='task',
            name='needs_help',
            field=models.BooleanField(default=False, verbose_name='Cần hỗ trợ'),
        ),
    ]
