# Generated by Cursor on 2026-02-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_task_help_and_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends_on',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='blocked_tasks',
                to='core.task',
                verbose_name='Phụ thuộc nhiệm vụ',
                help_text='Task này chỉ thực hiện được sau khi nhiệm vụ phụ thuộc hoàn thành.',
            ),
        ),
    ]
