# Generated by Cursor on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_task_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Ghim ưu tiên'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Nhãn'),
        ),
    ]
