# Generated by Django 6.0.2 on 2026-03-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_workflowpipelineevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowpipelineevent',
            new_name='workflow_pi_entity__eae923_idx',
            old_name='wpe_entity_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtasktemplate',
            new_name='workflow_ta_entity__2c3d99_idx',
            old_name='wft_entity_trigger_active_idx',
        ),
        migrations.AlterField(
            model_name='task',
            name='source_key',
            field=models.CharField(blank=True, help_text='Định danh duy nhất khi sinh tự động từ template. Dạng: wft-{template_id}-{entity_type}-{entity_id}', max_length=200, null=True, unique=True, verbose_name='Khóa nguồn gốc'),
        ),
        migrations.AlterField(
            model_name='workflowtasktemplate',
            name='description_template',
            field=models.TextField(blank=True, help_text='Hỗ trợ placeholder: {entity_code}, {entity_type}, {trigger}', verbose_name='Mô tả nhiệm vụ'),
        ),
        migrations.AlterField(
            model_name='workflowtasktemplate',
            name='due_in_days',
            field=models.PositiveSmallIntegerField(default=3, help_text='Số ngày kể từ ngày tạo task.', verbose_name='Hạn hoàn thành (ngày)'),
        ),
        migrations.AlterField(
            model_name='workflowtasktemplate',
            name='entity_type',
            field=models.CharField(help_text='VD: SalesOrder, Product', max_length=50, verbose_name='Loại đối tượng'),
        ),
        migrations.AlterField(
            model_name='workflowtasktemplate',
            name='title_template',
            field=models.CharField(help_text='Hỗ trợ placeholder: {entity_code}, {entity_type}, {trigger}', max_length=200, verbose_name='Tiêu đề nhiệm vụ'),
        ),
    ]
