# Generated by Django 6.0.2 on 2026-03-02 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_taskwatcher'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskwatcher',
            new_name='task_watche_user_id_f5295c_idx',
            old_name='task_watche_user_id_8d1637_idx',
        ),
        migrations.RenameIndex(
            model_name='taskwatcher',
            new_name='task_watche_task_id_a4dd2f_idx',
            old_name='task_watche_task_id_b0086c_idx',
        ),
    ]
