# Generated by Django 6.0.2 on 2026-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_seed_reports_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowtasktemplate',
            name='trigger',
            field=models.CharField(choices=[('SUBMIT', 'Nộp duyệt'), ('APPROVE', 'Phê duyệt'), ('REJECT', 'Từ chối'), ('POST', 'Đăng sổ (Post)'), ('VOID', 'Hủy (Void)'), ('RELEASE', 'Phát lệnh'), ('ISSUE', 'Cấp vật tư'), ('RECEIVE', 'Ghi nhận nhập/nhận'), ('CANCEL', 'Hủy chứng từ'), ('MANUAL', 'Thủ công')], max_length=50, verbose_name='Sự kiện kích hoạt'),
        ),
    ]
