# Generated by Django 6.0.2 on 2026-03-16 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_seed_stocktake_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomReportDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('SALES', 'Ban hang'), ('PURCHASE', 'Mua hang'), ('INVENTORY', 'Ton kho'), ('PRODUCTION', 'San xuat'), ('FINANCIAL', 'Tai chinh'), ('SHIPPING', 'Van chuyen'), ('WORKFORCE', 'Nhan su')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Nhap'), ('GENERATED', 'Da tao'), ('FINALIZED', 'Hoan tat'), ('ARCHIVED', 'Luu tru')], db_index=True, default='DRAFT', max_length=20)),
                ('is_system', models.BooleanField(db_index=True, default=False)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('schedule_frequency', models.CharField(choices=[('NONE', 'Khong lap lich'), ('DAILY', 'Hang ngay'), ('WEEKLY', 'Hang tuan'), ('MONTHLY', 'Hang thang')], default='NONE', max_length=20)),
                ('schedule_enabled', models.BooleanField(db_index=True, default=False)),
                ('schedule_time', models.TimeField(blank=True, null=True)),
                ('schedule_day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('schedule_day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('schedule_recipients', models.JSONField(blank=True, default=list)),
                ('schedule_name', models.CharField(blank=True, default='', max_length=100)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_generated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_run_status', models.CharField(blank=True, default='', max_length=20)),
                ('last_run_error', models.TextField(blank=True, default='')),
                ('last_run_summary', models.JSONField(blank=True, default=dict)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_reports_created', to=settings.AUTH_USER_MODEL)),
                ('last_generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_reports_last_generated', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_report_definitions',
                'ordering': ['-last_generated_at', '-updated_at', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CustomReportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('MANUAL', 'Thu cong'), ('SCHEDULED', 'Lich')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Thanh cong'), ('FAILED', 'That bai')], db_index=True, default='SUCCESS', max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('result_payload', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_report_runs_generated', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.customreportdefinition')),
            ],
            options={
                'db_table': 'custom_report_runs',
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='customreportdefinition',
            index=models.Index(fields=['report_type', 'status'], name='custom_repo_report__0f8d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='customreportdefinition',
            index=models.Index(fields=['schedule_enabled', 'schedule_frequency'], name='custom_repo_schedul_f5face_idx'),
        ),
        migrations.AddIndex(
            model_name='customreportdefinition',
            index=models.Index(fields=['is_system', 'code'], name='custom_repo_is_syst_b9863b_idx'),
        ),
        migrations.AddIndex(
            model_name='customreportrun',
            index=models.Index(fields=['report', 'generated_at'], name='custom_repo_report__cc0300_idx'),
        ),
        migrations.AddIndex(
            model_name='customreportrun',
            index=models.Index(fields=['status', 'generated_at'], name='custom_repo_status_9cb32c_idx'),
        ),
    ]
