# Generated by Django 6.0.2 on 2026-03-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_customreportdefinition_customreportrun_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-created_at', '-id'], name='auditlog_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', '-created_at', '-id'], name='auditlog_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['is_active', '-last_active', '-id'], name='usersession_active_last_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active', '-last_active'], name='usersession_user_active_idx'),
        ),
    ]
