# Generated by Django 6.0.2 on 2026-03-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_customreportdefinition_schedule_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customreportdefinition',
            name='schedule_frequency',
            field=models.CharField(choices=[('NONE', 'Không lập lịch'), ('DAILY', 'Hàng ngày'), ('WEEKLY', 'Hàng tuần'), ('MONTHLY', 'Hàng tháng')], default='NONE', max_length=20),
        ),
    ]
