# Generated by Django 6.0.2 on 2026-04-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_system_configuration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Gio ket thuc du kien'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Gio bat dau du kien'),
        ),
    ]
