# Generated by Django 6.0.2 on 2026-04-01 07:05

from datetime import datetime, time, timedelta

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _combine_local_date_and_time(date_value, time_value):
    naive_value = datetime.combine(date_value, time_value)
    return timezone.make_aware(naive_value, timezone.get_current_timezone())


def _backfill_task_schedule(apps, schema_editor):
    Task = apps.get_model('core', 'Task')

    queryset = Task.objects.all().only(
        'id',
        'due_date',
        'scheduled_start_time',
        'scheduled_end_time',
        'scheduled_start_at',
        'scheduled_end_at',
        'is_all_day',
    )
    for task in queryset.iterator(chunk_size=500):
        if task.scheduled_start_at or task.scheduled_end_at:
            continue
        if task.due_date is None:
            continue

        if task.scheduled_start_time is None and task.scheduled_end_time is None:
            task.scheduled_start_at = _combine_local_date_and_time(task.due_date, time.min)
            task.scheduled_end_at = _combine_local_date_and_time(task.due_date + timedelta(days=1), time.min)
            task.is_all_day = True
        else:
            start_at = _combine_local_date_and_time(task.due_date, task.scheduled_start_time or time.min)
            if task.scheduled_end_time is not None:
                end_at = _combine_local_date_and_time(task.due_date, task.scheduled_end_time)
                if end_at <= start_at:
                    end_at = start_at + timedelta(minutes=30)
            else:
                end_at = None
            task.scheduled_start_at = start_at
            task.scheduled_end_at = end_at
            task.is_all_day = False

        task.save(update_fields=['scheduled_start_at', 'scheduled_end_at', 'is_all_day'])


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_task_scheduled_end_time_task_scheduled_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_all_day',
            field=models.BooleanField(default=False, verbose_name='Ca ngay'),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_is_exception',
            field=models.BooleanField(default=False, verbose_name='Occurrence da override'),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_occurrence_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngay occurrence'),
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_occurrence_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Thu tu occurrence'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ket thuc tren lich'),
        ),
        migrations.AddField(
            model_name='task',
            name='scheduled_start_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bat dau tren lich'),
        ),
        migrations.CreateModel(
            name='TaskScheduleSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50, verbose_name='Loai doi tuong')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID doi tuong')),
                ('entity_code', models.CharField(blank=True, max_length=100, verbose_name='Ma doi tuong')),
                ('title', models.CharField(max_length=200, verbose_name='Tieu de mau')),
                ('description', models.TextField(blank=True, verbose_name='Mo ta mau')),
                (
                    'priority',
                    models.CharField(
                        choices=[('LOW', 'Thap'), ('MEDIUM', 'Trung binh'), ('HIGH', 'Cao'), ('URGENT', 'Khan cap')],
                        default='MEDIUM',
                        max_length=20,
                        verbose_name='Uu tien',
                    ),
                ),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Ghim uu tien')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Nhan')),
                ('is_blocking', models.BooleanField(default=False, verbose_name='Chan')),
                ('blocks_action', models.CharField(blank=True, max_length=50, verbose_name='Hanh dong bi chan')),
                ('anchor_start_at', models.DateTimeField(verbose_name='Moc bat dau')),
                ('anchor_end_at', models.DateTimeField(blank=True, null=True, verbose_name='Moc ket thuc')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='Ca ngay')),
                (
                    'recurrence_type',
                    models.CharField(
                        choices=[
                            ('DAILY', 'Hang ngay'),
                            ('WEEKDAY', 'Ngay lam viec'),
                            ('WEEKLY', 'Theo tuan'),
                            ('MONTHLY', 'Theo thang'),
                        ],
                        default='DAILY',
                        max_length=20,
                        verbose_name='Kieu lap',
                    ),
                ),
                ('interval', models.PositiveIntegerField(default=1, verbose_name='Chu ky')),
                ('weekdays', models.JSONField(blank=True, default=list, verbose_name='Ngay lap trong tuan')),
                ('ends_on', models.DateField(blank=True, null=True, verbose_name='Ket thuc vao ngay')),
                ('occurrence_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='So lan toi da')),
                ('is_active', models.BooleanField(default=True, verbose_name='Dang kich hoat')),
                ('last_materialized_to', models.DateField(blank=True, null=True, verbose_name='Da sinh den ngay')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'assigned_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='task_schedule_series_created',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Nguoi tao series',
                    ),
                ),
                (
                    'assigned_to',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='task_schedule_series_assigned',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Nguoi thuc hien',
                    ),
                ),
                (
                    'depends_on',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='dependent_schedule_series',
                        to='core.task',
                        verbose_name='Phu thuoc task',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Task schedule series',
                'verbose_name_plural': 'Task schedule series',
                'db_table': 'task_schedule_series',
                'ordering': ['title', 'id'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='schedule_series',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='occurrences',
                to='core.taskscheduleseries',
                verbose_name='Recurring series',
            ),
        ),
        migrations.RunPython(_backfill_task_schedule, _noop_reverse),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['scheduled_start_at'], name='tasks_schedul_ae2703_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['schedule_series', 'schedule_occurrence_date'], name='tasks_schedul_a02010_idx'),
        ),
        migrations.AddIndex(
            model_name='taskscheduleseries',
            index=models.Index(fields=['is_active', 'recurrence_type'], name='task_schedu_is_acti_609246_idx'),
        ),
        migrations.AddIndex(
            model_name='taskscheduleseries',
            index=models.Index(fields=['entity_type', 'entity_id'], name='task_schedu_entity__a00f7a_idx'),
        ),
        migrations.AddIndex(
            model_name='taskscheduleseries',
            index=models.Index(fields=['assigned_to'], name='task_schedu_assigne_af66d4_idx'),
        ),
    ]
